### PR TITLE
Patch day 2020-07-15 master => stable

### PR DESCRIPTION
**Pull request by mstormi**
Forwarding patches as of 2020/07/15 from master to stable branch

Signed-off-by: Markus Storm markus.storm@gmx.net

### CODE REVIEW

**Comment by mstormi** [comment]
All I did was a PR with the diff from master to stable
Why are there so many conflicts ? 

I believe I must be overlooking something substantial.

**Comment by ecdye** [comment]
Why not just reset stable to master? it would be easier and our git update process should handle it just fine.

**Comment by mstormi** [comment]
> Why not just reset stable to master? it would be easier and our git update process should handle it just fine.

Yes that would work but I hate stuff I don't understand. Also, the idea is to have a changelog.

**Comment by ecdye** [comment]
It will have a changelog let me try to make an example

**Comment by ecdye** [comment]
So it looks like there may not be a really good way to do it beacuse of the way GitHub compares the trees. THe cleanest way to do it may be to force reset stable to master and add a tag to stable indicating the patch day on the last commit.

**Comment by mstormi** [comment]
ok, forced stable to master and added a tag "patchday-20200715"

**Comment by ecdye** [comment]
Hmm, thats funny. I don't see the tag, you should add it to master and to stable it will help to give refrence and make it so it does not overwrite when we do future patchdays.

**Comment by mstormi** [comment]
You need to explicitly force transfer of tags .. either you forgot, or I did :)

**Comment by ecdye** [comment]
How could I have done it? I don't have write access to the repo. :)

**Comment by mstormi** [comment]
No I mean I think you also need to explicitly fetch them.

**Comment by ecdye** [comment]
No I was looking at github

**Comment by mstormi** [comment]
yeah it was me.
Can you see them now?

**Comment by ecdye** [comment]
Yep

**Comment by mstormi** [comment]
I've given you write access. Please use responsibly.

**Comment by ecdye** [comment]
I was not expecting this, however, I will.

**Comment by mstormi** [comment]
> I was not expecting this, however, I will.

You could review & eventually merge #1037 for a test.

BTW, we've been [iced](https://archiveprogram.github.com/).

**Comment by ecdye** [comment]
Will do.

> BTW, we've been iced.

No kidding, I guess as a final deadline for our next image we should strive for 2/2/2021 so it is preserved in the vault. That seems like a very achievable target, right?

**Comment by mstormi** [comment]
I'd like to get that out a little earlier 🧊

**Pull request merged**
