### PR TITLE
install ZRAM on Pi4_8GB too now that kernel oops was fixed

### PR DESCRIPTION
**Pull request by mstormi**
Fixes: #1135 

Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by mstormi** [comment]
@ecdye github told me
"At least 1 approving review is required to merge this pull request. "

It also said "As an administrator, you may still merge this pull request" so I did (it was a simple change)
but I think it's new that every PR requires approval, isn't it ?

**Comment by ecdye** [comment]
Yes, it is a simple change that was recently made by I think @kaikreuzer to help push us to more closely follow the contribution guidelines.

**Comment by mstormi** [comment]
ok... I'm still OK with having quick fixes without a PR or with a PR without approval but we should make sure the other(s) are aware there _was_ a change so we can act independent if necessary
Did you get informed about my fix on fix_premissions() ?

**Comment by ecdye** [comment]
> ok... I'm still OK with having quick fixes without a PR or with a PR without approval but we should make sure the other(s) are aware there _was_ a change so we can act independent if necessary
> Did you get informed about my fix on fix_premissions() ?

Yes, I for the most part share the same opinion as you, this project is small enough and has few enough contributors that I am comfortable with a small patch exception for maintainers.

**Pull request merged**
