### PR TITLE
Support zigbee network adapters

### PR DESCRIPTION
**Pull request by moodyblue**
Fixes https://github.com/openhab/openhabian/issues/1868

### CODE REVIEW

**Comment by moodyblue** [comment]
The syntax is correct. The shellcheck verifier is wrong.

**Comment by moodyblue** [comment]
Testing methodology:

1) Install Mosquitto
2) Plug zigbee usb dongle in usb2 port
3) Install Z2M: dongle is detected and user is prompted to confirm (no change to the existing action)
4) Verify `configuration.yaml` and connect to `openhabian:8081` to confirm that Z2M is running
5) Unplug zigbee usb dongle
6) Install Z2M: no dongle is detected. User is prompted to specify ip:port address of the coordinator (or <cancel>)
7) Verify `configuration.yaml` and connect to `openhabian:8081` to confirm that Z2M is running

**Comment by ecdye** [comment]
@moodyblue Can you fix the errors being thrown by ShellCheck to make the code follow our style guidelines? Once you have done that @mstormi or I would be happy to review this PR.

**Comment by moodyblue** [comment]
The code is Ok and the ShellCheck is wrong. If I follow ShellCheck's recommendation `nodejs-apps.bash` will not execute

**Comment by moodyblue** [comment]
Done

**Pull request closed without merging**
