### PR TITLE
Fix bluetooth package installation

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Comment by holgerfriedrich** [comment]
As @mstormi pointed out, #898 fails installing the packages due to the latest shellcheck change. The solution with smallest impact was to remove the quotes again and add an exception.
Other possible way would be to use an array.

Merging (small patch exception)

**Comment by mstormi** [comment]
See https://travis-ci.com/github/openhab/openhabian/jobs/338380361 and
https://travis-ci.com/github/openhab/openhabian/jobs/338380367
That's for x86 and 64-bit OS ARM.

Seems there's more packages that do not exist ?

**Comment by mstormi** [comment]
See also https://community.openhab.org/t/openhabian-install-fails-installing-additional-bluetooth-packages-failed-install-broken-and-unusable/99193

**Comment by holgerfriedrich** [comment]
@mstormi I do not understand what is going on here, I have those packages installed on my system! I had a closer look, the missing ones seem to be from `archive.raspberrypi.org/debian` and not from `raspbian.raspberrypi.org/raspbian`. Let's wait another few days and see the logs.
Thanks for the hotfix, this is good anyway.

**Comment by mstormi** [comment]
Note test builds only fail (due to packages missing) for specific architectures, it's never all of them.

**Pull request merged**
