### PR TITLE
Removed raspi-config as a tool

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
Fixes: #289

Signed-off-by: Elias Gabrielsson <elias@gabson.se>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
👍 
Happy you found my old ticket and solved it. The change confuses me though. Could you explain why this change is the solution?

**Comment by ThomDietrich** [comment]
If the command is not available: Show info text.
If the command is available: User explicitly installed it and we shouldn't mess with this!? Correct?

**Comment by EliasGabrielsson** [comment]
Okey, then I misunderstood the feature. I thought we like to force user to not use the `raspi-config` as it would interfere with `openhabian-config`.

I do not know why it wasn't working before... Strange behavior

**Comment by EliasGabrielsson** [comment]
What about just get rid of this removal?

**Pull request closed without merging**
