### PR TITLE
Add Raspberry Pi Imager and fix links

### PR DESCRIPTION
**Pull request by cyb3rko**
I just added the Raspberry Pi Imager and fixed some non-working or outdated links.
I hope everything is correct.

Have a great day and a great new year!

### CODE REVIEW

**Review by mstormi — CHANGES_REQUESTED** [review]
thanks
but please change the order of tools i.e. Etcher first as the recommendation.
No experiences with Raspi Image so won't recommend that for now.

**Comment by cyb3rko** [comment]
Ok. I now used it twice, works pretty similiar.
Shall I sign it as the check recommends?

**Comment by mstormi** [comment]
> 
> 
> Ok. I now used it twice, works pretty similiar.

Ok but we didn't so please for now change the order.

> Shall I sign it as the check recommends?

yes please.

**Comment by cyb3rko** [comment]
Ok, changed it and signed them.

**Comment by cyb3rko** [comment]
Oh, you've made a change request, sorry I didn't see it...

**Comment by mstormi** [comment]
thanks

**Pull request merged**
