### PR TITLE
build.bash usability improvements

### LINKED ISSUE #716: build.bash - usablity improvements
@holgerfriedrich 
build.bash shall check the second parameter to catch typos or unknown-parameters (who can remember if it is dev-git or git-dev?).

If a non-standard repo is used, filename of the generated image shall shall either include a string "custom" or include the repo and branch name. 

This is just a reminder for me to make a PR after shellcheck stuff is merged.

### PR DESCRIPTION
**Pull request by holgerfriedrich**
build.bash usability improvements, closes #716
Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Comment by mstormi** [comment]
@kaikreuzer can you please add @holgerfriedrich to the openHAB organization on Github ?

**Comment by kaikreuzer** [comment]
Done, added him as a contributor.

**Comment by holgerfriedrich** [comment]
Thanks, @kaikreuzer.

**Comment by mstormi** [comment]
remember to use rebase, not merge

**Pull request merged**
