### PR TITLE
Added dark theme to frontail for openHAB3 branch

### PR DESCRIPTION
**Pull request by florian-h05**
I have added a dark theme for the openHAB log viewer (frontail) in the openHAB3 branch.

You can select the darkmode by using the openhabian-config tool, when running in unattended mode the theme is set to the light theme as a default.

This is the new version of #1384

### CODE REVIEW

**Comment by florian-h05** [comment]
What is the problem in the _BATS / rpi4_bats_ check?

**Comment by mstormi** [comment]
rebase please

**Comment by florian-h05** [comment]
Sorry I have messed it up

I need help
My frontail branch was created out of the openHAB3 branch

**Comment by florian-h05** [comment]
Have I done the right?

**Pull request closed without merging**
