### PR TITLE
Add openHAB in Raspberry Imager

### PR DESCRIPTION
**Pull request by Larsen-Locke**
openHAB is currently not selectable as an image in the Raspberry Imager. This PR corrects this shortcoming.
For this, Raspberry Imager needs a json file on the download location of the image that contains the path to the current image and checksums. 
The json is generated from a template in build.bash and made available via the build workflow.
As soon as the json file is online, I would raise the corresponding issue at rpi-imager (analogue https://github.com/raspberrypi/rpi-imager/issues/427).
The PR solves my issue: https://github.com/openhab/openhabian/issues/1703
The option will look like this in the Raspberry Imager:
image

### CODE REVIEW

**Review by mstormi — COMMENTED** [review]
Let's see if I understand:
You generate hashes in build.bash and put them into a file called rpi-imager-openhab.json that you publish on GitHub as a release 'artifact' just like the images. For the current version that would point to
https://github.com/openhab/openhabian/releases/download/v1.7.4/rpi-imager-openhab.json 

You will provide a sniplet to the Raspi foundation to include https://github.com/openhab/openhabian/releases/download/latest/rpi-imager-openhab.json as the openHAB URL pointer in Raspi imager.

When I click on "latest" button on https://github.com/openhab/openhabian/releases/ it'll forward me to .../tag/v1.7.4/. However, artifact links seem to be specific to the version.
When I replaced "v1.7.4" in the image artifact link by "latest", I could not download the latest image. So I fear I believe https://github.com/openhab/openhabian/releases/download/latest/rpi-imager-openhab.json will not be a static valid URL.
So we need to update the foundation for every release ?

**Comment by Larsen-Locke** [comment]
Yes, that's the way it should work

> When I click on "latest" button on https://github.com/openhab/openhabian/releases/ it'll forward me to .../tag/v1.7.4/. However, artifact links seem to be specific to the version. When I replaced "v1.7.4" in the image artifact link by "latest", I could not download the latest image. So I fear I believe https://github.com/openhab/openhabian/releases/download/latest/rpi-imager-openhab.json will not be a static valid URL. and we would need to update the foundation for every release. 

No, it works. You just have to switch latest and download. You can check that  https://github.com/openhab/openhabian/releases/latest/download/openhabian-pi-raspios32-202206272122-git852c09c-crced70fd0c.img.xz works

See github doc Chapter 4. 
https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#linking-to-the-latest-release

The link would be:
https://github.com/openhab/openhabian/releases/latest/download/rpi-imager-openhab.json
I made a test build action and it worked. I tested the file locally and it worked.

**Comment by mstormi** [comment]
> The link would be:
> https://github.com/openhab/openhabian/releases/latest/download/rpi-imager-openhab.json
> I made a test build action and it worked. I tested the file locally and it worked.

Your current PR code would result in ..../download/latest/.... , or am I mistaken?

**Review by mstormi — APPROVED** [review]
LGTM now
D(id)N(ot)T(est)

**Comment by Larsen-Locke** [comment]
> Your current PR code would still result in ..../download/latest/.... , or am I mistaken?

No, your're absolutely right. My bad. Think I used the wrong version for testing. Now it should be correct. 

Problem was/ist that I can only make a build in my fork not a release (Error: Process completed with exit code ), so I don't have access to the generated files. I did a cat during build and used that, but is there a better way?

**Comment by mstormi** [comment]
> but is there a better way?

Dunno. Will merge and create a new release.

**Comment by Larsen-Locke** [comment]
The request for integration in rpi-imager is here:
[https://github.com/raspberrypi/rpi-imager/issues/472](https://github.com/raspberrypi/rpi-imager/issues/472)

**Pull request merged**
