### PR TITLE
copy openhabian_update() to /boot to be available to first-boot.bash

### LINKED ISSUE #986: Always use local repo on install?
@mstormi 

After #961 if I am correct the installer will always use the local repo. This is caused because of this:
``` bash
# must not remove for offline to work
#if [ -d /opt/openhabian ]; then cd /opt && rm -rf /opt/openhabian; fi
# shellcheck disable=SC2154
echo -n "$(timestamp) [openHABian] Cloning myself from ${repositoryurl}, ${clonebranch} branch... "
if ! openhabian_update; then
  echo "$(timestamp) [openHABian] The git repository on the public internet is not reachable."
  echo "$(timestamp) [openHABian] We will continue trying to get your system installed, but this is not guaranteed to work."
fi
ln -sfn /opt/openhabian/openhabian-setup.sh /usr/local/bin/openhabian-config
```
This would work, but `openhabian_update` is defined in `functions/openhabian.bash` which as far as I can tell is never sourced or included in `first-boot.bash` which means that it will always fail and default to the local repo, but this is not the right thing to do because then we won't update to the latest available version when we install from an image.

Is my logic right?

### PR DESCRIPTION
**Pull request by mstormi**
Fixes #986 

Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by ecdye** [comment]
Looks like a fix in theory. Now we need to see if it will actually work. Try getting rid of line 160 in `build.bash` so we can see in CI if it works CI should clone the right repo now anyway.

**Comment by mstormi** [comment]
like so?

**Comment by ecdye** [comment]
That should work.

**Comment by mstormi** [comment]
not there yet https://travis-ci.com/github/mstormi/openhabian/jobs/352403370#L423

**Comment by ecdye** [comment]
Hmm, make sure you bypass the stable default on first install and use whatever has been set in openhabian config and also make sure you are copying the .git directory of the openhabian repo when creating the image.

**Comment by mstormi** [comment]
It isn't about bypassing stable, that's what we normally want to use (except in CI).
When I introduced the stable branch, clonebranch is honored if set else stable is used as the default.
It was about clonebranch (to point to the CI branch) not being used.

So how about this now ? See first test build for maximum output.

**Comment by mstormi** [comment]
I'm still unsure how that'll work "in real life" for both cases, Inet there or Inet gone.

I've flashed a card with the beta image and copied first-boot.bash, helpers and openhabian.bash over.

With Inet on, install fails because "cannot change to /opt/openhabian" because "no such file or dir".
Duh. Yes of course it isn't there ....

**Comment by ecdye** [comment]
Well, that is a start. At least we are giving a partially complete system now. Looks like we are getting close. That seems to be working now. Now just refine it.

**Comment by mstormi** [comment]
Merge this ? The current state is broken IIRC.
Then refine what exactly ? Maybe I merge and you try yourself to see why java ain't there.

**Comment by ecdye** [comment]
Java doesn't install without internet because it us not included in the image yet and we have yet to resole dependency issues for it and zRam

**Pull request merged**
