### PR TITLE
do not run FireMotD -I in CI builds

### PR DESCRIPTION
**Pull request by mstormi**
Fixes: #1150  

Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Review by ecdye — COMMENTED** [review]
I am actually changing the install process as part of the prefetch for offline as I ran into issues so could you wait on this one?

**Comment by mstormi** [comment]
it's 2 lines only so why not just add them while you're working on it.

**Comment by ecdye** [comment]
fair enough

**Comment by mstormi** [comment]
I meant to say: add these lines to your working copy and close this PR when you're done.
Or do you want me to merge?

**Comment by ecdye** [comment]
Don't merge, I already have it added in my branch.

**Comment by mstormi** [comment]
fixed by #1121

**Pull request closed without merging**
