### PR TITLE
Add needed changes for openHAB 2.1 stable

### PR DESCRIPTION
**Pull request by ThomDietrich**
Hey! @kaikreuzer, @BClark09, @kubawolanin if you would like to have a quick look. It's a simple no-brainer change.

I've added all needed changes to openhabian-config for the upcoming 2.1 stable release in the short time I had in between meeting :smile: You'll see that the newly created function is 95% identical to the unstable function. That's for sure not elegant but the primary focus was to get a solution out there.

I've added a menu entry to the top level of the openhabian-config menu. This entry is temporary and only there to catch the eye of those less acquainted with the Linux world...

Will wait with the merge till the release is on its way.

Signed-off-by: Thomas Dietrich <Thomas.Dietrich@tu-ilmenau.de>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Also: https://github.com/openhab/openhab-distro/wiki/openHAB-2.1-Release-Notes#openhabian

**Comment by BClark09** [comment]
Looks good, I think there's [one more to catch though]( https://github.com/openhab/openhabian/pull/164/files#diff-cdd86852ccd3c255a7233e741f26a137R404). :wink:

**Comment by ThomDietrich** [comment]
darn! :see_no_evil:

**Comment by kaikreuzer** [comment]
Thanks, lgtm.
I am just wondering, how we will automate this all, what we are currently doing, once we have bi-weekly releases as requested by you 😲

**Comment by BClark09** [comment]
If we had a webpage that contained the following:

```
Latest Major Release: 2.1.0
Latest Minor Release: 2.1.1
Upcoming Release: 2.2.0
```

I can imagine it would be pretty simple?

**Comment by ThomDietrich** [comment]
@kaikreuzer I know what you mean :) I do not see a big problem here.
Because major releases are released every few months I've decided to include the version numbers for clarity. If we had more frequent updates I'd just add one function to switch between stable and unstable (and testing). New updates on the repository itself are nothing special and installed via a simple apt/yum/... upgrade and with the upgrade script this problem is now also solved for other setups.

@BClark09 shouldn't these be retrievable from cloudbees/bintray? At least cloudbees provides an API, one could also just parse the page at e.g. https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild

**Comment by kubawolanin** [comment]
> @BClark09 shouldn't these be retrievable from cloudbees/bintray?

It's [a built-in feature](https://stackoverflow.com/questions/18238616/jenkins-get-last-completed-build-status) of Jenkins. Take a look:
https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/api/json

:-)

**Comment by kaikreuzer** [comment]
>  I know what you mean :) I do not see a big problem here.

Ok then - let's try to incrementally increase the automation around the release process and we will get there one day 👍

**Pull request merged**
