### PR TITLE
pkill java after restart to eventually break out of startup loop

### PR DESCRIPTION
**Pull request by mstormi**
Fixes: #1870 

not 100% sure it's ok to remove the restart command, but the effect should be the same (except for the speedup, of course)

### CODE REVIEW

**Review by ecdye — CHANGES_REQUESTED** [review]
I would add back the restart after because it appears that the checks are failing because openHAB never actually restarts otherwise. See if adding it back helps and then we could go from there.

**Comment by mstormi** [comment]
will do but wonder if I can instead add "-now" to systemctl enable cmd some lines up

**Review by ecdye — APPROVED** [review]
LGTM, if you wanted to try adding the enable -now, I think it's worth a shot, but I wonder if that wouldn't cover all cases because of upgrades.

**Comment by mstormi** [comment]
Well EITHER `-now` and no additional restart OR no `-now` and restart but not both.
Switch or leave it like it is now with the merged PR?

**Pull request merged**
