### PR TITLE
Add openHAB generator based on Yeoman

### LINKED ISSUE #188: [Proposal] Integrate Yeoman openHAB generator
This suggestion is a shameless plug of mine :smile: 

Since we have a Node.js in place, we could integrate my [Yeoman openHAB generator](https://community.openhab.org/t/openhab-generator-design-your-smart-home-in-no-time/32250) into openHABian. It'll allow the newcomers to start off easily.

Here's the repository:
https://github.com/kubawolanin/generator-openhab

@ThomDietrich thoughts?

### PR DESCRIPTION
**Pull request by kubawolanin**
Closes #188

Signed-off-by: Kuba Wolanin <hi@kubawolanin.com> (github: kubawolanin)

### CODE REVIEW

**Comment by ThomDietrich** [comment]
I'll have to rethink the whole error catching and handling approach.

Would you also like to add a bash alias? https://github.com/openhab/openhabian/blob/master/includes/bash.bashrc#L95

**Comment by kubawolanin** [comment]
Hi Thom, 
Thank you for taking time for looking at it.
I've updated the docs and added an alias.
I don't think the auto-launch in INTERACTIVE mode is necessary.
Ambivalent opinions on that tool sort of let me down so I consider this change as temporary (until there's a UI-based solution that most people expects, that is).
Cheers!

**Comment by kubawolanin** [comment]
@ThomDietrich 🏓

**Comment by ThomDietrich** [comment]
Sorry 🙍‍♂️

**Comment by ThomDietrich** [comment]
Thanks Kuba! I've posted about it.

https://community.openhab.org/t/openhabian-hassle-free-openhab-setup/13379/1121

**Pull request merged**
