### PR TITLE
First implementation of tile function

### PR DESCRIPTION
**Pull request by ThomDietrich**
Resolves https://github.com/openhab/openhabian/issues/212

A first implementation, the function is not yet fully tested or included anywhere.

CC @kubawolanin @mstormi @rgerrans

Signed-off-by: Thomas Dietrich <Thomas.Dietrich@tu-ilmenau.de>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Looking good.
Everything tested and ready to merge. This will be a nice visual addition for the openHABian 1.4 and the openHAB 2.2 release. cc @kaikreuzer 

grafik

**Comment by ThomDietrich** [comment]
@mstormi could you please provide a screenshot of the FIND UI (rather than the marketing image)? Should be a screenshot, png, 350*200-250px and you can simply post it here. Thanks!

**Comment by ThomDietrich** [comment]
Thanks. This pull request has been integrated manually.

**Comment by mstormi** [comment]
find_ui

**Comment by ThomDietrich** [comment]
@kaikreuzer the "marketing image" indeed looks cooler than a few statistics. Are you still for screenshots-only? :)

**Comment by kaikreuzer** [comment]
I am for screenshots-only where it makes sense and looks good. I'm fine with the suggested marketing image here 👍

**Comment by ThomDietrich** [comment]
Okay then, let's leave as is. @mstormi thanks for the screenshot!

**Comment by ThomDietrich** [comment]
@kaikreuzer feel free to use the image above for the release, if it fits ;)

**Pull request closed without merging**
