### PR TITLE
Update menu.bash

### PR DESCRIPTION
**Pull request by MatzeMuc86**
Add experimental explanation for openjdk 17
Add activate explanation for openjdk

### CODE REVIEW

**Review by mstormi — CHANGES_REQUESTED** [review]
Please remove the "experimental" as it isn't a proper term to describe this option.
Installing JDK17 is not experimental. Running OH on Java17 is (somewhat).

Also please fix DCO.

**Comment by MatzeMuc86** [comment]
> Please remove the "experimental" as it isn't a proper term to describe this option. Installing JDK17 is not experimental. Running OH on Java17 is (somewhat).
> 
> Also please fix DCO.

Happy to correct. As I do not know the technical details, it is hard for me to find the proper wording. If I understood correct, Java 11 is kind of "default" while Java 17 is not? Maybe you can give me some background and I can suggest proper formulation for the menu. My goal would be to guide less experienced people to the potentially more stable / preferred option.

**Comment by mstormi** [comment]
add "(default)" to JDK11 menu option and remove the "(experimental)"

**Comment by MatzeMuc86** [comment]
> add "(default)" to JDK11 menu option and remove the "(experimental)"

Done.

I tried to activate DCO - I hope this works!

**Review by mstormi — APPROVED** [review]

**Comment by mstormi** [comment]
> I tried to activate DCO - I hope this works!

Unfurtunately not you didn't sign your commit
See explanation at https://github.com/openhab/openhabian/pull/1698/checks?check_run_id=7653786889

**Pull request merged**
