### PR TITLE
add to use NTP servers obtained from DHCP server

### LINKED ISSUE #998: no NTP
NTP not working on Raspbian.
For analysis and proposed solution see https://github.com/openhab/openhabian/issues/594#issuecomment-517051970
I believe that's still the situation. `/etc/dhcpcd.conf` has not NTP and `/etc/systemd/timesyncd.conf` is unconfigured hence not running even on latest Raspi OS.

### PR DESCRIPTION
**Pull request by mstormi**
Fixes #998 

Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by ecdye** [comment]
Have we figured out how to make it so that you can request a review from me using the GitHub UI yet, or is that still up in the air?

**Comment by mstormi** [comment]
> Have we figured out how to make it so that you can request a review from me using the GitHub UI yet, or is that still up in the air?

no haven't sorry

**Comment by mstormi** [comment]
Ethan I've given you 'Triage' access to the repo.
Don't have a PR at hand to try but I hope you should now show up in the list of potential reviewers,
You should also be able to manage issues/PRs now.

**Comment by ecdye** [comment]
I think it worked, because I can now manually request a review from you guys.

**Pull request merged**
