### PR TITLE
Fix .ssh error msg on tweaking

### LINKED ISSUE #799: ~openhabian/.ssh exists when tweaking from menu
see subject

### PR DESCRIPTION
**Pull request by mstormi**
to fix #799 

Signed-off-by: Markus Storm markus.storm@gmx.net (github: mstormi)

### CODE REVIEW

**Comment by mstormi** [comment]
fixes #799

**Comment by holgerfriedrich** [comment]
@mstormi Hi Markus, are you allowed to merge after a positive review, or do we need Thomas/Elias to do this?

**Comment by ThomDietrich** [comment]
Hey all,
Markus, feel free to merge.

@holgerfriedrich did you guys discuss adding you as a repository contributor in the past?

**Comment by ThomDietrich** [comment]
@mstormi @holgerfriedrich @EliasGabrielsson I would like to start a new conversation about the future of the openHABian project. Who else should be included? Would you like to get into a video call in the next couple of days?

**Comment by mstormi** [comment]
>  Markus, feel free to merge.

Now as the "required" status check doesn't pass (whyever, that's at least unrelated to my PR),
Github offers me to either "squash and merge" or "rebase and merge".
Just to make sure: I need to "rebase and merge", correct ?
Sorry for that silly question but I have not done it before and don't want to mess up things.
Am I right in assuming that if the check _had_ passed, Github _would have_ offered me a plain "merge" option ?

**Comment by mstormi** [comment]
> Would you like to get into a (video) call in the next couple of days?

Sure. Aren't we all at home ? Just make itfter work hours, please.
Dunno who else to invite.  I had a vid call with Elias using Hangouts a couple of weeks back and we went through this, but that's the last time I heard from him.

**Comment by holgerfriedrich** [comment]
@ThomDietrich a call would be helpful, I will try to take part. 
Adding us as contributors would be helpful to get open stuff to be merged. Overall strategy should be aligned.

**Comment by ThomDietrich** [comment]
Ah you didn't do a merge so far. I was not aware.
You always have the three options you can see. There is no simple merge but rather these three flavors. If you are not sure please read an article on them as this is important to know. Simply said: never use "Create merge commit" as it just clutters the history; use "Rebase and merge" when the individual commits (and their commit messages should be preserved, useful if a PR is complex); otherwise, most of the time, and if in doubt use "Squash and merge".

Call: @mstormi @holgerfriedrich @EliasGabrielsson @BClark09 when would you be available for approx 2h? https://dudle.inf.tu-dresden.de/openhabian/

**Comment by ThomDietrich** [comment]
Hey all, based on the poll, let's have a Hangouts call tomorrow at 20:00 (UTC+1)
So far @mstormi and @holgerfriedrich confirmed but everyone can join! See you there https://hangouts.google.com/call/2x8xlovcvZZRKq0VBiMFAEEI

**Pull request merged**
