### PR TITLE
Update a few links which lacked the `docs` path

### PR DESCRIPTION
**Pull request by brianwarner**
Just a few very minor tweaks to the links in the README.

Signed-off-by: Brian Warner <brian@bdwarner.com>

### CODE REVIEW

**Review by ecdye — APPROVED** [review]
LGTM

**Comment by mstormi** [comment]
I ommited that from the README which should essentially be a copy of the respective docs/openhabian.md section.
In that file however links must not start with docs/ because that file is uploaded to the official openHAB docs and leading "docs/" break links as it is currently the case. I'll fix that.

**Comment by ecdye** [comment]
Hmm, why does that break it? Are the maintainers of openHAB-docs aware of this bug?

**Comment by mstormi** [comment]
it is not a bug. It's a relative link relative to the perspective of the location of openhabian.md which is in the same docs/ subdir as itself (obviously) or the other .md files with READM.md being the sole exception. But README is not being linked to while openhabian.md is.
That's what it is no matter if in our repo or the openhabian docs location our docs/ dir is mirrored to.

**Comment by ecdye** [comment]
Ahh, ok I misinterpreted.

**Pull request merged**
