### PR TITLE
Prepare for shift to Bullseye

### PR DESCRIPTION
**Pull request by ecdye**
Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Review by mstormi — APPROVED** [review]
LGTM

let's build an image to test on real HW as next step

**Comment by ecdye** [comment]
@mstormi any idea why the Wireguard BATS test failed?

**Comment by mstormi** [comment]
Hmm, the "unsupported OS" output means that ALL helper checks i.e. is_pi || is_raspbian || is_raspios and is_debian() returned false

**Comment by ecdye** [comment]
Not sure, do you want to look into it? I have never really used the wireguard code or looked at it much.

**Comment by mstormi** [comment]
Fixed in https://github.com/openhab/openhabian/commit/dd8b4374836b6846617d56b4ec8cdedb2e077564
a case of buster specifics

**Pull request merged**
