### PR TITLE
Fix motd generation on migration

### LINKED ISSUE #1273: replace motd to match OH2 or OH3
on login to the box

make sure to change motd when migrating OH2<->OH3

### PR DESCRIPTION
**Pull request by ecdye**
Fixes #1273

Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Review by mstormi — APPROVED** [review]
LGTM
assume it worked in your test

**Comment by mstormi** [comment]
FWIW, the openHAB community be having a virtual meetup fortcoming Saturday 4pm CET and I'll have a short talk on openHABian.

Could you please review the hotspot thingy so I can put it in and promote stable, too ?

**Comment by ecdye** [comment]
Hmm, not really other than working on getting a better integration with OH3. I'll try to look at the hotspot PR tonight.

**Comment by mstormi** [comment]
any known issues with OH3 we would need to work on ?
turned out even "simple" installation is a mess, see https://github.com/openhab/openhab-distro/issues/1192

**Comment by ecdye** [comment]
Just smooth transitions. And also I don't think that the dashboard icons for logs,find, and others is used anymore so we could probably get rid of that and find a new way to present those. 

Overall not too much just the little things to add some polish.

**Comment by mstormi** [comment]
ok put up issue for stuff you find so we don't forget about

**Pull request merged**
