### PR TITLE
various Amanda docs fixes

### PR DESCRIPTION
**Pull request by mstormi**
Signed-off-by: Markus Storm markus.storm@gmx.net

### CODE REVIEW

**Comment by mstormi** [comment]
You should give it a try. It's more reading than actually works to install.
No backup, no pity !

**Comment by mstormi** [comment]
Travis build  hung and was canceled but Github does not notice and is still waiting ... my dummy changes trigger new builds, but Github still waits for the original one to finish.... no idea how to resolve that other than to wait for a timeout to (hopefully) occur by tomorrow.

**Comment by holgerfriedrich** [comment]
@mstormi rsync based backup in place ;-)
Is it possible to set the CI to optional and not required for merge until it works reliably?

**Comment by mstormi** [comment]
> @mstormi rsync based backup in place ;-)

rsync won't backup raw SD/partitions. Give it a try, use what you sell ;-)

> Is it possible to set the CI to optional and not required for merge until it works reliably?

Dunno how :( Will check back tomorrow.

**Comment by mstormi** [comment]
Seems all build checks hang and do not finish.
Just noticed that "squash and merge" is available to me while "rebase and merge" is not,
Whyever - will squash and merge.

**Pull request merged**
