### PR TITLE
Avoid running two DHCP clients (#1690)

### LINKED ISSUE #1690: Two IP addresses assigned to wlan0
## Issue information:
My RPi 4 gets assigned two IPv4 addresses to `wlan0` via DHCP. I haven't really done anything to the installation, it's my first time trying openHABian, so the "installation" is pretty much as it was "flashed". The image used is the 32 bit version of [openHABian v1.7.3](https://github.com/openhab/openhabian/releases/tag/v1.7.3).

While I haven't experienced a problem as a consequence of the double IP assignment, I haven't started installing bindings and "moving" the configuration from my existing openHAB 2.4 installation (on a Windows box), so I have no idea if it will actually pose a problem or not once being "set to work". It doesn't look right anyway, and as I'm planning to reserve a fixed IP to the RPi's MAC address in the DHCP server, I'm worried that it could cause problems when a lease is requested twice with the same MAC address.

As Raspberry Pi OS/openHABian is new to me, and I've mostly been using Fedora when using Linux in the last years, I don't have much overview over what systems are used to configure the network and such. I have managed to find what seems to be the cause of the double IP address lease though, as show below: Both `dhclient` and `dhcpcd` seems to be operating, each reserving one IPv4 address. IPv6 is disabled as it's not used on my home network. So, I guess the question is, why are they both making leases?

## Debug information:
```
> less /var/log/syslog

Jun  4 04:51:27 habbo dhcpcd[382]: wlan0: carrier acquired
Jun  4 04:51:27 habbo dhcpcd[382]: wlan0: connected to Access Point `xxxxx'
Jun  4 04:51:27 habbo dhcpcd[382]: DUID xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
Jun  4 04:51:27 habbo dhcpcd[382]: wlan0: IAID 32:52:53:ff
Jun  4 04:51:27 habbo dhcpcd[382]: wlan0: adding address fe80::364:507b:c5ee:6aa0
Jun  4 04:51:27 habbo dhcpcd[382]: ipv6_addaddr1: Permission denied
Jun  4 04:51:27 habbo dhcpcd[382]: received SIGPIPE
Jun  4 04:51:27 habbo wpa_action: WPA_IFACE=wlan0 WPA_ACTION=CONNECTED
Jun  4 04:51:27 habbo wpa_action: WPA_ID=0 WPA_ID_STR= WPA_CTRL_DIR=/var/run/wpa_supplicant
Jun  4 04:51:27 habbo systemd[1]: Starting System Logging Service...
Jun  4 04:51:27 habbo wpa_action: ifup wlan0=default
Jun  4 04:51:27 habbo dhcpcd[382]: wlan0: rebinding lease of 10.72.64.103
Jun  4 04:51:27 habbo dhclient[653]: Internet Systems Consortium DHCP Client 4.4.1
Jun  4 04:51:27 habbo dhclient[653]: Copyright 2004-2018 Internet Systems Consortium.
Jun  4 04:51:27 habbo dhclient[653]: All rights reserved.
Jun  4 04:51:27 habbo dhclient[653]: For info, please visit https://www.isc.org/software/dhcp/
Jun  4 04:51:27 habbo dhclient[653]:
Jun  4 04:51:27 habbo dhcpcd[382]: wlan0: probing address 10.72.64.103/24
Jun  4 04:51:27 habbo dhclient[653]: Listening on LPF/wlan0/dc:a6:32:52:53:ff
Jun  4 04:51:27 habbo dhclient[653]: Sending on   LPF/wlan0/dc:a6:32:52:53:ff
Jun  4 04:51:27 habbo dhclient[653]: Sending on   Socket/fallback
Jun  4 04:51:27 habbo dhclient[653]: DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 8
Jun  4 04:51:27 habbo dhcpcd[382]: wlan0: soliciting an IPv6 router
Jun  4 04:51:27 habbo rsyslogd: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.  [v8.2102.0]
Jun  4 04:51:27 habbo rsyslogd: [origin software="rsyslogd" swVersion="8.2102.0" x-pid="662" x-info="https://www.rsyslog.com"] start
Jun  4 04:51:27 habbo systemd[1]: Started System Logging Service.
Jun  4 04:51:27 habbo dhclient[653]: DHCPOFFER of 10.72.64.102 from 10.72.64.1
Jun  4 04:51:27 habbo dhclient[653]: DHCPREQUEST for 10.72.64.102 on wlan0 to 255.255.255.255 port 67
Jun  4 04:51:27 habbo dhclient[653]: DHCPACK of 10.72.64.102 from 10.72.64.1
Jun  4 04:51:28 habbo kernel: [   16.107566] Bluetooth: Core ver 2.22
Jun  4 04:51:28 habbo kernel: [   16.107702] NET: Registered PF_BLUETOOTH protocol family
Jun  4 04:51:28 habbo kernel: [   16.107720] Bluetooth: HCI device and connection manager initialized
Jun  4 04:51:28 habbo kernel: [   16.111141] Bluetooth: HCI socket layer initialized
Jun  4 04:51:28 habbo kernel: [   16.111177] Bluetooth: L2CAP socket layer initialized
Jun  4 04:51:28 habbo kernel: [   16.111218] Bluetooth: SCO socket layer initialized
Jun  4 04:51:28 habbo kernel: [   16.129722] Bluetooth: HCI UART driver ver 2.3
Jun  4 04:51:28 habbo kernel: [   16.129751] Bluetooth: HCI UART protocol H4 registered
Jun  4 04:51:28 habbo kernel: [   16.129873] Bluetooth: HCI UART protocol Three-wire (H5) registered
Jun  4 04:51:28 habbo kernel: [   16.131328] Bluetooth: HCI UART protocol Broadcom registered
Jun  4 04:51:28 habbo systemd[1]: Starting Load/Save RF Kill Switch Status...
Jun  4 04:51:28 habbo systemd[1]: Started Configure Bluetooth Modems connected by UART.
Jun  4 04:51:28 habbo systemd[1]: Started Load/Save RF Kill Switch Status.
Jun  4 04:51:28 habbo systemd[1]: Created slice system-bthelper.slice.
Jun  4 04:51:28 habbo systemd[1]: Starting Raspberry Pi bluetooth helper...
Jun  4 04:51:28 habbo bthelper[716]: Raspberry Pi BDADDR already set
Jun  4 04:51:28 habbo systemd[1]: Finished Raspberry Pi bluetooth helper.
Jun  4 04:51:28 habbo systemd[1]: Starting Bluetooth service...
Jun  4 04:51:28 habbo dhclient[653]: bound to 10.72.64.102 -- renewal in 38881 seconds.
...
Jun  4 04:51:29 habbo systemd[1]: Started Hostname Service.
Jun  4 04:51:32 habbo dhcpcd[382]: wlan0: leased 10.72.64.103 for 86400 seconds
Jun  4 04:51:32 habbo dhcpcd[382]: wlan0: adding route to 10.72.64.0/24
Jun  4 04:51:32 habbo dhcpcd[382]: wlan0: adding default route via 10.72.64.1
Jun  4 04:51:32 habbo systemd[1]: Stopping Network Time Synchronization...
Jun  4 04:51:32 habbo systemd[1]: systemd-timesyncd.service: Succeeded.
Jun  4 04:51:32 habbo systemd[1]: Stopped Network Time Synchronization.
Jun  4 04:51:32 habbo systemd[1]: Starting Network Time Synchronization...
Jun  4 04:51:33 habbo systemd[1]: Started Network Time Synchronization.
Jun  4 04:51:33 habbo systemd[1]: Stopping Network Time Synchronization...
Jun  4 04:51:33 habbo systemd[1]: systemd-timesyncd.service: Succeeded.
Jun  4 04:51:33 habbo systemd[1]: Stopped Network Time Synchronization.
Jun  4 04:51:33 habbo systemd[1]: Starting Network Time Synchronization...
Jun  4 04:51:33 habbo systemd[1]: systemd-rfkill.service: Succeeded.
Jun  4 04:51:33 habbo bthelper[874]: Changing power off succeeded
Jun  4 04:51:33 habbo systemd[1]: Started Network Time Synchronization.
Jun  4 04:51:33 habbo dhcpcd[382]: forked to background, child pid 876
Jun  4 04:51:33 habbo systemd[1]: Started DHCP Client Daemon.
Jun  4 04:51:33 habbo systemd[1]: Reached target Network is Online.
Jun  4 04:51:33 habbo systemd[1]: Starting Samba NMB Daemon...
Jun  4 04:51:33 habbo systemd[1]: Started openHAB - empowering the smart home.
```

## System information:
32 bit openHABian 1.7.3 running from the onboard microSD card slot on a Raspberry Pi 4 4GB. No hardware (HATs, USB dongles etc.) attached to the RPi yet.

```
> cat /etc/os-release

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
```
> uname -m

armv7l
```

### PR DESCRIPTION
**Pull request by Nadahar**
This hopefully fixes #1690. It does so by reverting fc1943afa22208a40e0c372d6271989f9af24adb and 99a8be1770bc95d4925ad44cd516531ba25ce851 so that `avahi-autoipd` and `isc-dhcp-client` aren't installed. Removing `avahi-autoipd` should also make adding `noipv4ll` to `/etc/dhcpcd.conf` unnecessary.

If somebody actually needs AutoIP and thus installs `avahi-autoipd`, they wouldn't want the functionality to be blocked by the `noipv4ll` statement. I have no idea whether `avahi-autoipd` will work without `isc-dhcp-client`, but it's not defined as a dependency, only as "recommended" - so that's basically anybody's guess. At least there's a chance that it would work if they do:
```
apt-get install --no-install-recommends avahi-autoipd
```
Ideally this should be tested/verified and documented *if* it does work, for the very few that might need it.

Please note that I have no way to test/verify this except knowing that uninstalling `avahi-autoipd` and `isc-dhcp-client` makes my installation behave correctly and only assign one IP address to `wlan0`. Think of this more as a suggestion than as a PR that is ready to merge.

### CODE REVIEW

**Comment by mstormi** [comment]
Thanks for digging deep.
I agree that we should not need to have avahi-autoipd there in default openHABian, anyone who wants to can install it themself.
Then again I don't know what other side effects your removal PR might bring and I have no means to test either in a universal sense other than to merge and see what happens to people on new installations.
Guess I have to sleep it over.

Meanwhile, could you please fix signoff on your commit to fix the DCO test ? thx

**Comment by Nadahar** [comment]
Regarding the DCO stuff, I read your "contribution rules" and they clash with a strict rule of mine: Always be anonymous in public online, not because my identity is some kind of secret but because I don't want search engines to index everything I do on my name and make it very easy to get an overview over my activities.

I've had to abandon PRs for the same reasons before, and it's also the reason I haven't bothered trying to make PRs for openHAB itself. These changes are tiny though, so it wouldn't cost you many seconds to do the same changes in a commit of your own.

If I could find the images built by GitHub Actions for this PR, I could at the very least flash one to my SD card and to a "fresh install" to verify that things "seems to work ok". Are they possible for me to get my hands on somewhere?

**Comment by Nadahar** [comment]
I've done a new installation using the image built by Github Actions on this PR. I can't find any problems as this is now. The change that makes the difference is to stop writing a WiFi configuration to `/etc/network/interfaces`.

It seems to me that neither `avahi-autoipd` nor the `noipv4ll` setting in `/etc/dhcpcd.conf` is directly related to the "dual DHCP client issue". I'm pretty sure that this branch would also fix #1456, since it avoids having two DHCP clients running creating all kinds of havoc. Therefore I've built this image without the `noipv4ll` setting in `/etc/dhcpcd.conf`. Auto-IP now also works like I think it should, if I disable my DHCP server it will assign a `169.254.x.x` address, but with the DHCP running it will assign one leased from the DHCP server. The only change I can find when setting `noipv4ll` in `/etc/dhcpcd.conf` is that without the DHCP server, no IP will be assigned at all. It's hard to judge what is the "most desirable" behavior, but I guess I'd say that having it assign an auto-IP when no DHCP is available is marginally better - though probably completely irrelevant for most users.

From what I can deduct from my own testing and some online searching, `dhcpcd` doesn't use `avahi-autoipd`, but has its own implementation instead. Thus, only the `noipv4ll` setting matters for `dhcpcd`. `dhclient` on the other hand seems to need `avahi-autoipd` to assign auto-IPs, but as long as the choice has been made upstream to use `dhcpcd` instead of `dhclient`, the only sane thing to do is to stay far away from anything `dhclient`. So, I'd say that installing `avahi-autoipd` should be completely unnecessary, but is most likely harmless. I left it in during the build for "isolation purposes" when testing, to narrow the changes down as much as possible. Since it doesn't seem to be related to the dual IP issue, one could argue that it has nothing to do with this PR - at the same time I'd say that not installing packages that aren't needed or helpful should generally be the preferred behavior.

The good thing after finally getting rid of `dhclient` is that now network configuration is much, much simpler. All is done in `/etc/dhcpcd.conf`. It works with DHCP out of the box, and I can't see why openHABian would need to touch the file at all, except for during the "emergency hotspot configuration". That means that people can configure it manually if they so wish, and there should be no "interference" from openHABian in that configuration, making things suddenly break.

I've now tested this with a static IP configured in `/etc/dhcpcd.conf` and with a "static fallback" IP, as shown in the comments in the same file. Both solutions work as expected. This means that it should be safe to remove the "advise" for people not to configure openHABian with a static IP. It should just be pointed out that any such changes *must* be made in `/etc/dhcpcd.conf` and that `/etc/network/interfaces` *must* be left alone.

Since this PR can never be merged, I haven't rebased the commits (or even bothered to GPG sign them). That makes it easier to see the changes if you chose to use any part of this.

**Comment by mstormi** [comment]
I'd suggest to re-remove avahi-autoipd as you say it's unneeded and we can save on valuable RAM that way.
If you put that change back in (i.e. avahi-autoipd out) I can merge it without that you would need to sign.

**Comment by Nadahar** [comment]
@mstormi I agree, it's done.

**Pull request merged**
