### PR TITLE
Re-add rpi-update to basic packages

### PR DESCRIPTION
**Pull request by ThomDietrich**
CC @mues-lee 

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

### CODE REVIEW

**Comment by mues-lee** [comment]
the whole `if is_pi is unnessesary
- `rpi-update` is still there and working before it was removed by 'cond_redirect rm -f /usr/bin/rpi-update'
- `rpi-update` is in the apt repository, so it got already to the newest version, when we fired apt update and & apt upgrade in the first boot

**Comment by ThomDietrich** [comment]
I remember there were times when it wasn't part of the raspbian image (maybe the ua-netinst image). So you are telling me it is redundant because it's available on a Raspbian image by default?

**Comment by mues-lee** [comment]
yes exactly

**Comment by ThomDietrich** [comment]
👍

**Pull request merged**
