### PR TITLE
Ngnix certbot provided by Buster repo; closes #636

### LINKED ISSUE #636: Ngnix install fails on Buster if domain is specified
Ngnix install fails in case the user specifies a domain name.

The error leaves the apt system broken
`E: Malformed entry 2 in list file /etc/apt/sources.list.d/backports.list (Component)`
`E: The list of sources could not be read.`
until you drop the corrupted line from `backports.list`

Root cause is in `packages.bash` line 571, where certrepo is undefined for Buster.

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
Good find.
But your fix will break installation for Stretch.
Why not just update the package file with `buster` ?

**Comment by holgerfriedrich** [comment]
Both Stretch and old Jessie define certbotrepo. I think it will not break something...
Or did I make a mistake?

**Comment by EliasGabrielsson** [comment]
I think we need this: ~

```
elif is_buster; then
            certbotrepo="buster"
fi
```

wdyt?

**Comment by holgerfriedrich** [comment]
No, die Buster certbot ist not in backports anymore but included in the standard repo.

**Comment by BClark09** [comment]
@EliasGabrielsson the travis build failed but I don't think it's related to this PR. How can we get it to rerun? Happy to merge anyway.

**Comment by EliasGabrielsson** [comment]
I think we need to look over the java installation routine. Usually that which fails.

**Pull request merged**
