### PR TITLE
[OH3] Update openHABian logo

### PR DESCRIPTION
**Pull request by ecdye**
Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Comment by mstormi** [comment]
shouldn't that go into the openHAB3 branch only ?

**Comment by ecdye** [comment]
Nah, it's a logo change in general. It can be incorporated now.

**Comment by mstormi** [comment]
> Nah, it's a logo change in general.

they won't change the logo on 2.5.x so we should not either I'd think.
It's also nice to have a (big) visual indication which version you're on so please put that onto OH3 branch only.

**Comment by ecdye** [comment]
Ok, I'll just push this to the openHAB3 branch and close this PR.

**Pull request closed without merging**
