### PR TITLE
Revert "fix frontail service startup (#672)"

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
This reverts commit b52bd84a0be2f9abc48e1ce1533579c30e181635.

### CODE REVIEW

**Comment by mstormi** [comment]
[This](https://travis-ci.com/mstormi/openhabian/jobs/228052105) is from my current-most build. Line 1294 is why I changed frontail path to /usr/local/bin.
So can the path depend on npm config or package version ?
Shouldn't we play it safe and add at least a link ?

**Comment by mstormi** [comment]
Even worse now: https://travis-ci.com/mstormi/openhabian/jobs/228391498
Where's frontail installed ??

**Comment by EliasGabrielsson** [comment]
It works in master so it must be something in your branch or temporary install issues. See: https://travis-ci.org/openhab/openhabian/builds/576713562

**Comment by mstormi** [comment]
It's because npm lives in /usr/local/lib/node_modules in the base image I'm using.
As it might be the same on other non-RPi-image installs I guess we should check for that and adapt $frontail_base

**Comment by EliasGabrielsson** [comment]
Sounds fair. Lets make the installation aware of where node_modules are.

**Comment by mstormi** [comment]
https://github.com/openhab/openhabian/pull/688

**Pull request merged**
