### PR TITLE
testing/milestone repo moved to Artifactory due to space limitations

### PR DESCRIPTION
**Pull request by mstormi**
Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by BClark09** [comment]
We made this change to the repo yesterday. Remember to pull the latest master into your master's fork before you make new branches.

**Comment by mstormi** [comment]
Hmm doing too many things at the same time.

Debugging why my own install fails, I saw this. It's choking on apt-get update for the the stable repo due to bad key. Did you also do anything on that ?

Ign:5 https://dl.bintray.com/openhab/apt-repo2 stable Release.gpg
Reading package lists...
E: The repository 'https://dl.bintray.com/openhab/apt-repo2 stable Release' is not signed.

**Comment by BClark09** [comment]
I believe the Bintray repo (stable) is broken until we can update the private key but I do not have this. In the mean time I am trying to find a workaround to.resolve the issue.

**Comment by mstormi** [comment]
Can we put up the stable package to bintray as well? We could change openHABian code then.

**Pull request closed without merging**
