### PR TITLE
Add and configure frontail

### LINKED ISSUE #28: New optional component frontail
I was wondering if it was possible to add the component: https://github.com/mthenw/frontail to the build, its a very nice light weight application for streaming logs to the browser. It's a tail -F with UI.

It makes keeping a log window open nice and easy and i dont need two SSH sessions open.

### PR DESCRIPTION
**Pull request by ThomDietrich**
Resolves #28 

@jameshiscott @kubawolanin @LeDumpier 

Finally! I've looked into frontail and like it a lot. Thanks for all the info, help and instructions you gave in #28. I've added all needed steps to openHABian and invested a few more minutes this evening to add an openHAB (PaperUI) theme and a highlighting schema to the mix.

Please test! ;) I'd invite everyone to contribute style and highlighting improvements. I've only covered the most common log lines.

grafik

Signed-off-by: Thomas Dietrich <Thomas.Dietrich@tu-ilmenau.de>

### CODE REVIEW

**Comment by jameshiscott** [comment]
Looks ace, will give it a try. Had a feeling it would fit well with you. Thanks @ThomDietrich

**Comment by ThomDietrich** [comment]
I've just merged it. You'll have to execute "Update" and run "Basic Setup" from the menu. After that it should be available under http port 9001.
Thanks again for your help and sorry for the four months delay 😨

Please let me know what you think of the styling, I'd like to further improve it over time.

**Comment by LeDumpier** [comment]
I should get some time to test it this weekend on a freash OpenHABian 
install, thanks for the effort for setting it up.

Then what's next? Adding Squeezeserver to the installation too maybe? ;)

**Comment by ThomDietrich** [comment]
> Squeezeserver

Not very homeautomation'ly, is it? I'd like to contentrate on components that are closely linked to openHAB and common systems we interact with...

**Comment by LeDumpier** [comment]
Hi @ThomDietrich 

The installation via openhabian-config is absolutely seamless, thank you. Couldn't be easier :)

I wonder if you could point me in the right direction on how I can bypass the Openhab theme as I want to use it in HabPanel and it would be nice for it to blend in.

Thanks again

**Comment by LeDumpier** [comment]
I might add though the OpenHAB theming is very nice touch :)

**Comment by ThomDietrich** [comment]
Thanks man ;)
Yes that's easy, first the all-solving solution: the openHAB theme is just that, a website (i.e. css) theming. Hence you can use css to modify whatever you want. After the installation you'll find the file [`includes/frontail-theme.css`](https://github.com/openhab/openhabian/blob/master/includes/frontail-theme.css) under `/usr/lib/node_modules/frontail/lib/web/assets/styles/openhab.css`. Just add whichever modification you wish for.

Second solution: frontail already [provides an option](https://github.com/mthenw/frontail#usage) to hide the topbar. Just modify the service file under `/etc/systemd/system/frontail.service` =)

**Comment by LeDumpier** [comment]
Thank you for the pointers. Also thanks again for your work on OpenHABian, it goes a long way in helping newcomers to get into the world of OH2. Good stuff

**Pull request merged**
