### PR TITLE
Fix NGINX configuration

### PR DESCRIPTION
**Pull request by BClark09**
NGINX setup is currently broken due to it trying to uncomment the wrong line numbers.

 - Moved the NGINX setup script to its own file.
 - The uncomment/comment function now removes/adds a keyword, instead of pointing to a specific line number.

Still need to test this change, but submitting it for review and visibility.

Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
Thanks Ben.
Will look into it when time permits.

**Comment by EliasGabrielsson** [comment]
@BClark09 My plan is to write up a suite of test for this functionality which will be a separate PR.
After that PR is merged you will need to rename the file to `ngnix.bash` and the test will trigger.

**Comment by EliasGabrielsson** [comment]
Sorry for not completing this review yet. Tried to do some test cases but the code were needed to be rewritten in a more modular sense. You are not forgotten Ben.

**Comment by thedannymullen** [comment]
Did this get implemented?  I tried to install nginx today and it threw a failcode.

I will dive in to debug later today but curious if the issue is the same as stated here.

**Comment by altair2010** [comment]
can you resolve conflicts, i will try the patch on my config
=> i am blocked by the issue #539

**Comment by mstormi** [comment]
Hi @BClark09 could you please have another look and this and resolve conflicts ?
Please also have a look at #786, thanks

**Comment by mstormi** [comment]
Superseded/fixed by #818

**Pull request closed without merging**
