### PR TITLE
Moved to stable artifactory repo

### PR DESCRIPTION
**Pull request by mstormi**
Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by mstormi** [comment]
@BClark09 milestones and snapshots already use testing and unstable artifactory repos. Same URL now as the new stable.
So those will not need changes ?

Please verify I caught all instances of repo use.

**Review by ecdye — APPROVED** [review]
LGTM

**Review by BClark09 — CHANGES_REQUESTED** [review]
Thanks @mstormi,

https://github.com/openhab/openhabian/blob/e6556293b2ccddc5bc99569d6f4eac8db92e8509/functions/openhab.bash#L88 

should be changed to https://openhab.jfrog.io/artifactory/api/gpg/key/public

As mentioned in https://github.com/openhab/openhab-linuxpkg/pull/200, I'm planning to add the repo list file inside the package itself, and then eventually the signing key, this would mean future versions of openHAB can be installed simply by downloading and installing the `.deb` file.

**Comment by mstormi** [comment]
Thanks Ben, I've addressed those.
Asking just for safety: is the repo ready? 
If so, please merge.

**Review by BClark09 — APPROVED** [review]
Thanks @mstormi, the repo is ready so is safe to transfer now.

**Pull request merged**
