### PR TITLE
Fix check for Java arch when updating Zulu

### LINKED ISSUE #1013: java update misbehavior ?
I told openhabian to switch to Adopt.
1) OH was down before but the upgrade code made it start
2) I did systemctl stop openhab2  which did stop thaht start, but then Zulu was installed ??

Vorbereitung zum Entpacken von .../adoptopenjdk-11-hotspot-jre_11.0.7+10-2_armhf.deb ...
Entpacken von adoptopenjdk-11-hotspot-jre (11.0.7+10-2) ...
adoptopenjdk-11-hotspot-jre (11.0.7+10-2) wird eingerichtet ...
update-alternatives: /usr/lib/jvm/adoptopenjdk-11-hotspot-jre-armhf/bin/java wird verwendet, um /usr/bin/java (java) im automatischen Modus bereitzustellen
update-alternatives: /usr/lib/jvm/adoptopenjdk-11-hotspot-jre-armhf/bin/jjs wird verwendet, um /usr/bin/jjs (jjs) im automatischen Modus bereitzustellen
update-alternatives: /usr/lib/jvm/adoptopenjdk-11-hotspot-jre-armhf/bin/keytool wird verwendet, um /usr/bin/keytool (keytool) im automatischen Modus bereitzustellen
update-alternatives: /usr/lib/jvm/adoptopenjdk-11-hotspot-jre-armhf/bin/pack200 wird verwendet, um /usr/bin/pack200 (pack200) im automatischen Modus bereitzustellen
update-alternatives: /usr/lib/jvm/adoptopenjdk-11-hotspot-jre-armhf/bin/rmid wird verwendet, um /usr/bin/rmid (rmid) im automatischen Modus bereitzustellen
update-alternatives: /usr/lib/jvm/adoptopenjdk-11-hotspot-jre-armhf/bin/rmiregistry wird verwendet, um /usr/bin/rmiregistry (rmiregistry) im automatischen Modus bereitzustellen
update-alternatives: /usr/lib/jvm/adoptopenjdk-11-hotspot-jre-armhf/bin/unpack200 wird verwendet, um /usr/bin/unpack200 (unpack200) im automatischen Modus bereitzustellen
update-alternatives: /usr/lib/jvm/adoptopenjdk-11-hotspot-jre-armhf/lib/jexec wird verwendet, um /usr/bin/jexec (jexec) im automatischen Modus bereitzustellen
OK

$ systemctl start openhab2.service
Job for openhab2.service canceled.

$ java_zulu_update_available Zulu8-32
2020-07-03_16:54:32_CEST [openHABian] Installing Java Zulu prerequisites (libc, libstdc++, zlib1g)... OK
2020-07-03_16:54:32_CEST [openHABian] Downloading Java Zulu 8 32-Bit OpenJDK...
$ wget -qO /opt/jdk/zulu.tar.gz https://cdn.azul.com/zulu-embedded/bin/zulu8.46.0.225-ca-jdk8.0.252-linux_aarch32hf.tar.gz

### PR DESCRIPTION
**Pull request by ecdye**
Fixes #1013

Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Comment by mstormi** [comment]
openhabian does not let me install *any* java because of partial removal

+ java -version
Error: missing `client' JVM at `/opt/jdk/zulu11.39.61-ca-jdk11.0.7-linux_aarch32hf/lib/client/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
+ return 4
+ '[' 4 -ne 0 ']'
+ whiptail --msgbox 'There was an error or interruption during the execution of:\n  "40 | openHAB related"\n\nPlease try again. If the error persists, please read /opt/openhabian/docs/openhabian-DEBUG.md or https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md how to proceed.' 14 80

**Comment by ecdye** [comment]
Somehow your system got screwed up, that does not happen on my end, did you hit Ctrl-C at some point?

**Comment by ecdye** [comment]
Yep, just checked after merge and it works fine on my end, you may need to manually remove the old install or reinstall.

**Comment by mstormi** [comment]
yes I killed the openhabian-setup process. edited the code to make it skip that check now reinstalling

**Comment by ecdye** [comment]
That probably broke it somehow.

**Comment by mstormi** [comment]
Actually I'm having problems since with connecting to myopenhab. Searching yields nothing except many responses saying to update Java, one of them to delete any from a list of packages, `java-common` being among those.
I noticed `java-common` IS installed on my openHABian. Removing it resulted in Zulu8-embedded being removed, too (I installed that inbetween for a test to enforce switching java).

So independent of whether that'll fix my problem I think we need to
- uninstall oldish packages when switching away from that (zulu-embedded, others ?)
- remove(?) java-common pkg at least when switching to Zulu(?)
I removed it and it got installed again when I switched to Adopt.

But that made my openhabcloud finally connect again.

**Pull request merged**
