### PR TITLE
Zram disclaimer

### PR DESCRIPTION
**Pull request by mstormi**
Display disclaimer on installation that zram is BETA and used at one's own risk.
There's also a link to the status thread on forum.

Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
You need to start isolate your commit in different branches. Now you have included a lot of irrelevant changes not concerning the topic.
I will only put effort of reviewing stuff rebased on top of master.

**Comment by mstormi** [comment]
Ups. That was a mistake. I took the fast lane to get this out fast but guess I chose the wrong repo to clone from... it's actually just 2 files to change.

**Comment by mstormi** [comment]
ok here you are

**Comment by EliasGabrielsson** [comment]
Better but not really there yet.
(DO) I want you to _**rebase**_ your changes ontop of "master" . 
(DON'T) Merge master into your feature branch like you have done now.

Take your time and once for all get the concept right, it will save you time.
Give this a try: https://www.atlassian.com/git/tutorials/merging-vs-rebasing (~20min incl. exercises)

**Comment by EliasGabrielsson** [comment]
I like the changes though so will merge when you get your `git` commits right. 👍

**Comment by mstormi** [comment]
>  (DON'T) Merge master into your feature branch like you have done now.

I know the difference, but here I merged to resolve a single file conflict using merge right in Github UI when that popped up for a reason I haven't fully understood yet.... maybe I created my branch from my local master and would have needed to update that before.

**Comment by mstormi** [comment]
yes hadn't fetched master so used an outdated source. Commits should be fine now, no?

**Comment by mstormi** [comment]
@EliasGabrielsson are you gonna merge this and the build refactoring soon ?
It's becoming cumbersome to rebase/forward-distribute changes to so many PRs/repos as I have currently open.

**Comment by EliasGabrielsson** [comment]
Just want to make sure the CI will run through first. (Got hanged up on that initial state sometimes fails.)

About the buildsystem, will focus on reviewing the Shellcheck PR first. Thereafter I will start reviewing the build/test refactoring. Got limted time in life so you would need to accept some wait time unfortunate.

**Comment by mstormi** [comment]
> Just want to make sure the CI will run through first. (Got hanged up on that initial state sometimes fails.)

not sure what you mean there but if I can help with that let me know

**Pull request merged**
