### PR TITLE
Make hotspotpw parameter configurable as GitHub Secret

### PR DESCRIPTION
**Pull request by mstormi**
Github env name HOTSPOTPW

Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Review by ecdye — APPROVED** [review]
LGTM, DNT

**Comment by ecdye** [comment]
By default, the secrets are empty right now. Do we want to set them to the default `openhabian` password we use elsewhere?

**Comment by mstormi** [comment]
I had set them as Github secrets but they disappear if you do.
Is that a Github bug?

**Comment by ecdye** [comment]
> I had set them as Github secrets but they disappear if you do.

What do you mean? You set them to the default?

> Is that a Github bug?

I'm not sure, I've never played with GitHub Secrets before. Did you look in the documentation?

**Comment by mstormi** [comment]
> What do you mean? You set them to the default?

Yes to "openhabian" (you can under 'Settings' - Secrets)

> I'm not sure, I've never played with GitHub Secrets before. Did you look in the documentation?

Me neither. Did not find anything mentioned.

**Comment by ecdye** [comment]
Hmm, that's odd. Is it blank in the resulting image as well?

**Comment by mstormi** [comment]
apparently so at least with my forked repo this was the case.

**Comment by ecdye** [comment]
Hmm, maybe just a GH bug. Perhaps we should wait to merge until sorted out.

**Comment by ecdye** [comment]
I've looked into this, and I think that being unable to view the current secret is a security feature. Feel free to merge if you would like.

**Comment by mstormi** [comment]
did you test? As I wrote I believe the password was gone when I build an image last time but I'm not sure any more

**Comment by mstormi** [comment]
just tested, it kept my Github-provided password so will merge

**Pull request merged**
