### PR TITLE
nginx config: keywords

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Configuration for nginx is broken since the config template changes.
This PR resolves the conflicts of PR #540 and supersedes PR #786.

Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Just as a side note: Do you think this would be interesting? https://github.com/openhab/openhabian/issues/313

**Comment by holgerfriedrich** [comment]
@ThomDietrich 
> Just as a side note: Do you think this would be interesting? #313

Not sure. I would not expose http to the outside anyway and recommend disabling http.
But I am not running nginx - so it is up to someone else.

**Comment by ThomDietrich** [comment]
> expose http to the outside 

Not what I suggested. Doesn't matter now. We can discuss #313 later

**Comment by holgerfriedrich** [comment]
@mstormi could you pls merge and close the related issues?
@thomdietrich any progress on write access?

**Comment by mstormi** [comment]
> 
> 
> @mstormi could you pls merge and close the related issues?

Can you please list the superseded PRs and fixed issues you want me to close ?

**Comment by holgerfriedrich** [comment]
Closes #539 #540 #786, thanks @mstormi

**Comment by mstormi** [comment]
> @ThomDietrich any progress on write access?

Try requesting here https://github.com/orgs/openhab/teams/openhabian-maintainers/teams
Will see if I can confirm that.

**Comment by ThomDietrich** [comment]
Just contacted Kai about the permissions. Sorry for the delay guys.

**Comment by mstormi** [comment]
Created a team "refocusian" but failed to add Holger as he's not a member of "openhab" organization ?
Haven't found where to change that, probably Kai has to.
PS yep, silly name.

**Pull request merged**
