### PR TITLE
Frontail service fix

### PR DESCRIPTION
**Pull request by mstormi**
Not sure changing path in https://github.com/openhab/openhabian/pull/672 was a good idea, some people to complain on the forum.
Played it safe and now allow for both locations.
Also included https://github.com/openhab/openhabian/issues/431

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
These line should rather be:
```
Environment=PATH=/usr/local
```
```
WorkingDirectory=/usr/bin/
```
Sorry for not noticed that before. What kind of errors do people have?
Are there only new installation which have trouble. Regarding your git conflict resolve it by rebase ontop of upstream master as usual.

**Comment by mstormi** [comment]
https://community.openhab.org/t/frontail-not-starting-after-fresh-install-openhabian/80597
only new installs apparently
Put in /usr/local/bin now 2 times.
What git conflict do you mean?

**Comment by EliasGabrielsson** [comment]
I must been dizzy, I mixed up `Frontail` and `FireMotD`. 
The service file was before your "fix", just checked on a new installation.
There must been some other funky things going on for the one in the forum.

**Comment by mstormi** [comment]
So the service file was correct before my yesterday's "fix" and is broken now so I just reverted that.
_I_ might have been dizzy yesterday too but I wonder why I had to change the path for the install test to complete. Do you mind if I keep the link /usr/local/bin/frontail->/usr/bin/frontail for safety reasons? I also left the WorkingDir change in as that might help some.

**Comment by EliasGabrielsson** [comment]
Installation works at least on x86 (see pushed test.) If there are some issue they are ARM / Debian Buster specific. Let's first of all get grip of what is the cause of the issue.

**Comment by EliasGabrielsson** [comment]
The old place for Frontail installation was: `/usr/local/bin/frontail`
The new one is: `/usr/bin/frontail`

**Comment by mstormi** [comment]
ok will open another issue in case something comes up new

**Pull request closed without merging**
