### PR TITLE
Amanda dir name should be /var/backups

### LINKED ISSUE #162: Running amanda setup causes error
It looks like /var/backup does not exist when running the amanda setup from the menu.

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/usr/local/bin/openhabian-config: line 1313: /var/backup/.amandahosts: No such file or directory
/usr/local/bin/openhabian-config: line 1314: /var/backup/.amandahosts: No such file or directory
/usr/local/bin/openhabian-config: line 1315: /var/backup/.amandahosts: No such file or directory
/usr/local/bin/openhabian-config: line 1316: /var/backup/.amandahosts: No such file or directory
chown: cannot access ‘/var/backup/.amandahosts’: No such file or directory

### PR DESCRIPTION
**Pull request by mstormi**
Signed-off-by: Markus Storm markus.storm@gmx.net (github: mstormi)
Closes #162

### CODE REVIEW

**Comment by kubawolanin** [comment]
Just a side note - please add `Closes #162` so the related issue is closed after your PR is merged.

**Comment by ThomDietrich** [comment]
Hello @mstormi, thanks for looking into the issue. The solution looks good to me. You still need to sign your commits as per the openHAB contributing rules. Ideally you'd squash all your commits to one and sign this one - you can alternatively add your signed-off-by in the PR description.

Thanks again!

**Comment by mstormi** [comment]
ok, I signed in the first PR comment

**Comment by ThomDietrich** [comment]
Thanks.

**Pull request merged**
