### PR TITLE
fix samba password change

### PR DESCRIPTION
**Pull request by mstormi**
Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey @mstormi this change was introduced by @EliasGabrielsson in https://github.com/openhab/openhabian/pull/248. I expected it to be an improvement of some sort. @EliasGabrielsson do you remember the reason?

I'll go ahead and merge

**Comment by mstormi** [comment]
FWIW, someone also mentioned on the forum that changing the system passwd does not work, but I couldn't reproduce that, it worked for me

**Comment by ThomDietrich** [comment]
I saw that. Thanks for testing!

**Comment by EliasGabrielsson** [comment]
The fix was for an typo I made in the original pull req. The case statement was wrong.
The system change password should™ work, its just a basic unix command. @mstormi Do you have any link to the issue, at least which thread it was?

**Comment by mstormi** [comment]
https://community.openhab.org/t/openhabian-v1-4-released/37398/25

As I already commented, changing that one worked for me

**Pull request merged**
