### PR TITLE
only add openhabian user to backup group if it exists

### LINKED ISSUE #533: Setting up amanda without openHABian user fails
The line @ [backup.sh](https://github.com/openhab/openhabian/blob/master/functions/backup.sh#L166) will fail if the openhabian user does not exist. It is likely trying to set ownership to the default user's group for easy access.

We should check if the openhabian user exists first before executing such a command, and make the inputs to the usermod function variables.

A secondary question: Should the openhabian group exist for manual installs too?

See: https://community.openhab.org/t/fatal-error-when-installing-amanda-backup-via-openhabian-config/68229/4

### PR DESCRIPTION
**Pull request by mstormi**
fix #533 

Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
Should not this group be created if it not exist?
Will amanda work without it?

**Comment by mstormi** [comment]
Amanda does not need it to run (as long as the "backup" user does exist) so it does not need to be created. This is just to answer Benjy's #533.

**Comment by mstormi** [comment]
@BClark09  Benjy, are you ok with this fix, can we merge it ?

**Comment by BClark09** [comment]
Yes, thanks @mstormi!

**Pull request merged**
