### PR TITLE
buildsystem refactoring

### PR DESCRIPTION
**Pull request by mstormi**
Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by mstormi** [comment]
btw, there still is a "Vagrantfile".
Do you have any plans with Vagrant or can we delete it ?

**Comment by mstormi** [comment]
I have a couple of problems with Github as well, it does not accept uploads at times or fails inexplicably.

**Comment by EliasGabrielsson** [comment]
Please fix all CI related issues first. 
I will review the code after that. 
I also noted that you included a lot of new code. 
Could that be fetched upstream somehow?

**Comment by mstormi** [comment]
err ... which open CI related issues do you mean, am I overlooking something ?
Just rebased FWIW.

And that "lot of new code" actually isn't a lot, it's all from the balena guys but it's distributed across a number of places and isn't available as an upstream repo so we can't simply clone/download. It's also supposed to be static.

**Comment by mstormi** [comment]
Still looking after a couple of build errors, but these appear unexpectedly in openhabian-setup.sh at different, varying stages.
It's still sort of non-deterministic .... but then again I think that's what openhabian-setup is - which is why it fails for a couple of people and we cannot reproduce their problems. Probably because of changing external factors such as inet and repo connectivity and package versions .

**Comment by mstormi** [comment]
Finally found the "cache", it was the script to clone itself. Now while it is right to clone the openhab/openhabian repo for the production, I of course need *my* development repo to be cloned.
Parametrized that in Dockerfile now.

**Comment by EliasGabrielsson** [comment]
Just checking, are you aware of the command `./test.bash docker-full` in the repository?
That will run all test locally, presumed that you have a local docker instance running.

**Comment by mstormi** [comment]
no wasn't aware of that, thanks
yeah really struggling to get the bats tests working that did work with your stretch image
then again docker on RPi has its issues

**Comment by mstormi** [comment]
no wasn't aware of that, thanks.
I'm really struggling to get the bats tests working that did work with your image still based on stretch.
Using local docker, do you know of a means to save the container save in an intermediate state (after openhabian-setup was run) as that's a prerequisite to the bats tests and getting there takes most of the time. For now I have to do all the install every time just to test a minor change in the bats test routines at the end of the process.

**Comment by EliasGabrielsson** [comment]
Take a look at the `docker commit` command.
I brief guide below: https://www.techrepublic.com/article/how-to-commit-changes-to-a-docker-image/

**Comment by mstormi** [comment]
I had it working but after upgrading to latest docker-ce package, I now get this on builds.
Any idea what's wrong there?
Hints on google are docker cannot reach DNS but that's fine, also added it to /etc/docker/daemon.json.

Step 4/26 : RUN apt-get update -qq     && apt-get install -y -qq --no-install-recommends systemd systemd-sysv git wget python3 python3-pip apt-utils     && rm -rf /var/lib/apt/lists/*
 ---> Running in 397ab94ce6cb
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Failed to init resolver - res_init (116: Stale file handle) System error resolving 'deb.debian.org:http' - getaddrinfo (116: Stale file handle)
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Failed to init resolver - res_init (116: Stale file handle) System error resolving 'security.debian.org:http' - getaddrinfo (116: Stale file handle)
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Failed to init resolver - res_init (116: Stale file handle) System error resolving 'deb.debian.org:http' - getaddrinfo (116: Stale file handle)
W: Failed to fetch http://archive.raspbian.org/raspbian/dists/buster/InRelease  Failed to init resolver - res_init (116: Stale file handle) System error resolving 'archive.raspbian.org:http' - getaddrinfo (116: Stale file handle)
W: Failed to fetch http://archive.raspberrypi.org/debian/dists/buster/InRelease  Failed to init resolver - res_init (116: Stale file handle) System error resolving 'archive.raspberrypi.org:http' - getaddrinfo (116: Stale file handle)
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by mstormi** [comment]
I think I'm done now with refactoring the build system.
Got my docker back working, latest version 19 has issues.

I touched a couple of code lines along the way where I noticed issues with the build.
The one thing left to resolve is the final Grafana test failing. I don't find the reason for that but it is not related to the build system. Might be buster related or anything. Maybe you can have a look.

Please review.

**Comment by mstormi** [comment]
As requested will split into smaller patches. Mind the order to apply:
https://github.com/openhab/openhabian/pull/681

**Comment by mstormi** [comment]
I'm still using the "build" branch to develop/test stuff and will keep it somewhat up to date with HEAD. But don't merge it, that's what PRs 681...684 are for.

Currently I'm puzzling about [these build errors](https://travis-ci.com/mstormi/openhabian/jobs/228907681): there's NO service running on final dashboard access test??
I thought this might be attributed to ARM on x86 emulation but it happens with the Intel NUC image, too ... any ideas welcome.

**Comment by mstormi** [comment]
Superseded by #681 - #684

**Pull request closed without merging**
