### PR TITLE
Fix build.bash parameter check

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Comment by mstormi** [comment]
is that all what needs to be fixed in build.bash ?
Don't want to do many micro PRs.

**Comment by holgerfriedrich** [comment]
Yes, don't know why we did not notice that normal image creation is broken since last update....

**Comment by mstormi** [comment]
> Yes, don't know why we did not notice that normal image creation is broken since last update....

because we don't test for it ? Can you come up with a BATS or docker test case of building the image ?

**Comment by mstormi** [comment]
what about #856 ?

**Comment by holgerfriedrich** [comment]
@mstormi opened https://github.com/orgs/openhab/teams/openhabian-maintainers/discussions/15

**Pull request merged**
