### PR TITLE
Install npm to fix frontail install

### PR DESCRIPTION
**Pull request by mstormi**
Fixes: #1597 

Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Review by ecdye — CHANGES_REQUESTED** [review]
Not sure why this broke all of the sudden but I would rather just install `npm` at the same time as `nodejs` so why dot you move this to lines 47 & 49.

**Comment by mstormi** [comment]
> 
> 
> Not sure why this broke all of the sudden but I would rather just install `npm` at the same time as `nodejs` so why dot you move this to lines 47 & 49.

See original code, it wasn't executed when either NodeJS was already installed (which it was in Raspi OS)
OR when it was NOT a RPi0. So effectively it never was.
I don't wanna break that logic by moving this down.

if node_is_installed || ! is_armv6l; then return 0; fi

**Comment by ecdye** [comment]
> > Not sure why this broke all of the sudden but I would rather just install `npm` at the same time as `nodejs` so why dot you move this to lines 47 & 49.
> 
> See original code, it wasn't executed when either NodeJS was already installed (which it was in Raspi OS) OR when it was NOT a RPi0. So effectively it never was. I don't wanna break that logic by moving this down.
> 
> if node_is_installed || ! is_armv6l; then return 0; fi

But this new code has the same problem does it not? If NodeJS is installed it won't execute and it nodeJS is not installed it and we are not on a RPi0 we will install npm before we install NodeJS, right? That is what I don't want if anything we should install both at the same time.

**Comment by mstormi** [comment]
Yes it has the same behavior. But that has not been a problem so far so why do you call it a problem? And then why change?
And I don't get why you insist on installing both at the same time. Why isn't the current proposal code (doing npm first nodejs later) fine ?

I don't mind changing but I think I didn't get your point so as you can edit, I suggest you do to suit your idea.

**Comment by ecdye** [comment]
> Yes it has the same behavior. But that has not been a problem so far so why do you call it a problem? And then why change? And I don't get why you insist on installing both at the same time. Why isn't the current proposal code (doing npm first nodejs later) fine ?
> 
> I don't mind changing but I think I didn't get your point so as you can edit, I suggest you do to suit your idea.

I just think that it is much cleaner and more effective to install them both at the same time rather than doing one then the other. It also reduces the amount of code overall.

**Review by ecdye — APPROVED** [review]

**Comment by mstormi** [comment]
did you test it works ? nodejs_is_installed at the beginning checks for node OR npm so if node is there but npm is not it still won't install, will it?
That's why I took the apparently longer route I did.

**Comment by ecdye** [comment]
Yes it appears to work for me, but I can change it to ensure that if one or the other is not there to just install both again.

**Comment by mstormi** [comment]
I'm still unsure we talk about the right point so again, to be explicit about the important point: did you test with a fresh image? 
if at the early stage in automated installation where we have nothing but Raspi OS, the first line in nodejs_setup() calls node_is_installed() and returns(!) when node_is_installed() returns true which is when EITHER node OR npm is installed.
So if node is there but npm is not, it won't get installed, leading to the frontail error later. Or am I wrong here ?

(and note Raspi OS can also change at any time in the future, too, to have either of these packages installed or not, and I want a permanent, future proof solution to work independent of what's in the image or not)

**Comment by ecdye** [comment]
Yes I did test and it worked on a fresh image. I'm going to make the change so that both npm and nodeJS must be installed to let the check pass. if one or the other is missing it will reinstall once I make the change.

**Comment by ecdye** [comment]
OK so really what needs to happen is when npm or nodejs get mixed up and are not both installed just reinstall nodejs let me issue the fix.

**Comment by ecdye** [comment]
@WolfgangSn try again now.

**Pull request merged**
