### PR TITLE
Added dark theme to frontail for openHAB3 branch

### PR DESCRIPTION
**Pull request by florian-h05**
I have added a dark theme for the openHAB log viewer (frontail) in the openHAB3 branch.

You can select the darkmode by using the openhabian-config tool, when running in unattended mode the theme is set to the light theme as a default.

This is the new version of #1385 

Sorry that I have messed everything up a few times but I am new to GitHub and so I have to learn a much

### CODE REVIEW

**Comment by ecdye** [comment]
@florian-h05 thanks for your contribution.

You have changed many files unrelated to frontail in this PR, please fix. I would suggest simple checking out the openHAB3 branch and making changes on it using `git checkout openHAB3`.

**Comment by florian-h05** [comment]
@ecdye 

So I have to use the openhab:openHAB3 branch and then create a new forked branch from it where I can create the dark theme?

**Comment by ecdye** [comment]
> @ecdye
> 
> So I have to use the openhab:openHAB3 branch and then create a new forked branch from it where I can create the dark theme?

Yes, or you could base it off of the master branch and create a dark theme for OH2 and then migrate it to OH3.

**Comment by florian-h05** [comment]
Okay thank you very much I am going to create a new branch from openHAB3 and then create a new pull request

**Comment by florian-h05** [comment]
My new pull request is #1391

**Pull request closed without merging**
