### PR TITLE
Use the official Azul distribution repo via apt-get

### PR DESCRIPTION
**Pull request by libo**
Azul seems provides official repos
This PR uses them via `apt-get` as suggested here:
https://docs.azul.com/zulu/zuludocs/Content/ZuluReleaseNotes/Troubleshooting.htm#Azul_Repo_Tips

and here:
https://community.openhab.org/t/howto-install-zulu-embedded-java-on-raspberry-pi-3/22589

Alternative of: https://github.com/openhab/openhabian/pull/643 as suggested by @mstormi  
cc: @EliasGabrielsson

### CODE REVIEW

**Comment by libo** [comment]
Tested on my raspberry pi 4 and installs fine

**Comment by BClark09** [comment]
Hi @libo, thanks for the PR.

Azul do not appear to update the repos for armhf. The latest version available in that repo is revision 153 but the minimum recommended revision for openHAB is 161.

**Comment by libo** [comment]
The version is not the latest and greatest:
```
> java -version
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)
```

But OpenHAB seems to work just fine and really snappy compared to my Synology... so far.
Can we ask Azul to put some love and update the repos somehow?

**Comment by BClark09** [comment]
If I remember correctly there is an issue with cryptography below revisions 161. You'll be unable to use the marketplace properly.

> Can we ask Azul to put some love and update the repos somehow?

I think someone has tried, but they are only community offered (can't seem to find the issue/comment though).

**Comment by EliasGabrielsson** [comment]
I have tried to communicate to Azul before, but please reach out to them.

Ben is correct about the cryptography issue.
Currently only the x86 repository are updated so we need to stay on `.tar` method.
I have in mind to update the 32-bit Java PR to also contain an update script.

**Comment by EliasGabrielsson** [comment]
I close this PR now but we will have an eye on Azuls repositories if they decide to upgrade the `Java-Embedded` software. Currently only the enterprise version are updated. (Two different products.)

**Pull request closed without merging**
