### PR TITLE
WIP travis cleanup

### PR DESCRIPTION
**Pull request by holgerfriedrich**
tests to fix CI, can only be done in main repo.
do not review/merge

### CODE REVIEW

**Comment by holgerfriedrich** [comment]
@mstormi  how did you test the bats stuff? It seems the run does not use the bats files from the commit, but the version which is currently master on github...

**Comment by mstormi** [comment]
I have put a lot of work into reworking the build system. Please have a look at my PRs #681 -  #684
before moving on with trying to fix the CI.
So if you can quickly fix builds please do but I remember I tried several months ago. Also my PRs will change that again anyway so I suggest to rather focus on those.

On the bats stuff, there's a major rework of all tests in #682. I suggest you cross-check with that before you continue here.

I also actually remember hitting the major issue that the build system will clone the latest openHABian master repo. But that is the production repo so it does not contain the fixes you just made and want to test before merging into master. So the first thing I changed was to clone the right (dev) repo. See https://github.com/openhab/openhabian/pull/681#issuecomment-561825758 .

**Comment by mstormi** [comment]
PS and I guess we need another shellcheck iteration after this merge orgy

**Comment by holgerfriedrich** [comment]
@mstormi still waiting for access. I just wondered why the first-install.bash failed in travis, got this fixed by f62764cced58bf31a5de30e673154d810772891f , but then ended up on some blocking bats scripts. For my repo the travis integration works, here we seem to need some tuning of the settings (status not reported back).
Still waiting for the group access, will have a look at the PRs once I have a bit more time...

**Comment by holgerfriedrich** [comment]
@mstormi I see...

**Pull request closed without merging**
