### PR TITLE
Update first-boot.sh

### PR DESCRIPTION
**Pull request by Alluuu**
If updating repositories and upgrading installed packages fails, give it another chance with reinstating dpkg

Signed-off-by: Alari Truuts<Alari.Truuts@gmail.com> (github: Alluuu)

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey! great work and thanks for the PR. We could merge as is but I think this step would be better suited as part of the routine before this one in line 98. Wdyt?

**Comment by ThomDietrich** [comment]
My main point is, we should be able to do this more elegantly. Should be is key here. I am not aware how it plays exactly and how we could improve this.

Fun fact: we had this extra step in the code base at some point but removed it when it wasn't needed anymore.

Anyhow, nothing speaks against merging the PR as is. Thanks for your contribution!!

**Comment by ThomDietrich** [comment]
Ah one thing you missed, please sign your work. See contributing. The result has to look similar to:

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

**Comment by Alluuu** [comment]
@ThomDietrich  Thanks for the input. I'm sure there could be a more elegant solution - the current solution at least quickly solves the issue for the time being.

Without changing code I can't write a commit message, any ideas on how to sign it off so it'd count?

**Comment by ThomDietrich** [comment]
Just put it in the first message this time.

**Comment by ThomDietrich** [comment]
Great. Done

**Pull request merged**
