### PR TITLE
Prepare for beta test of AdoptOpenJDK

### PR DESCRIPTION
**Pull request by ecdye**
Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Comment by ecdye** [comment]
@mstormi Do you want me to create the community post or would you like to. Either way, we should wait to merge until we have updated the files with the actual link.

**Comment by mstormi** [comment]
I will, here's the draft:
Dear community members,

you might know that OH3 is targeting to run on Java 11. To make a future transition happen as smooth as possible,
we have added two new Java 11 providers as options to openHABian in addition to the standard Azul Zulu JRE 8.
I'd kindly request all of you to embark on a testdrive of these and their implementation in openHABian.
While not guaranteed, our internal testing at least gave hope that Java 11 is also compatible with 2.5, so you should be able to run your home on that new Java.

(as root)
```
cd /opt/openhabian
git checkout testbuild
```

Please report problems back to the forum by opening a new thread and use the 'java-test' tag.
Make sure that your problem is really caused by the new Java provider before posting.
If not 100% sure please cross-check by downgrading to your old Java version (just don't change anything else).


You can change Java at any time via openhabian-configmenu 40, including going back to the standard Zulu 8 (no need to changfe openHABian branches).
You can return to latest standard openHABian by switching branches back either by use of the new menu 01 or manually by
```
cd /opt/openhabian
git checkout stable
```
if you want to use the (also new) 'safe' branch to contain validated fixes only or `git checkout master`if you want to keep getting latest updates to openHABian as fast as possible to run on your system.

**Comment by mstormi** [comment]
Yes I am right now creating the post (will create but hide until we're ready).
Are we? Is the code ready ?
Is it really 88 files to patch ? you sure nothing went wrong?

**Comment by ecdye** [comment]
My input,

Dear community members,

As you may know, OH3 is targeting a Java 11 runtime. As a result, to make the future transition as smooth as possible, we have added two new Java 11 providers as available options for openHABian, in addition to the standard Azul Zulu JRE 8.
I'd kindly request that all who are willing to embark on a test-drive of these components and their implementation in openHABian please read on for instruction on how to do so.
While not guaranteed, internal testing has shown that for the most part, Java 11 is also compatible with openHAB 2.5, so you should be able to run your home on the new version of Java without being on an unstable version of openHAB.

To switch to the testing branch please run the following as root:

``` bash
cd /opt/openhabian
git checkout testbuild
```

Please report any  problems back to the forum by opening a new thread and use the 'java-test' tag.
Also, please make sure that your problem is really caused by the new Java provider before posting.
If you are not 100% sure please cross-check by downgrading to your old Java version (just don't change anything else).

You can change the Java provider/version at any time via `openhabian-config` menu 40, including going back to the standard Zulu 8 (no need to change openHABian branches again).
You can return to standard openHABian branch by switching branches back either by use of the new menu 01 or manually by running the following as root:

``` bash
cd /opt/openhabian
git checkout stable
```

This will switch you back to the new 'safe' branch that contains validated fixes only. If you want to test new non-validated code then you can either use the new menu 01 or issue the following commands as root to switch to the master branch:

``` bash
cd /opt/openhabian
git checkout master
```

This will allow you to receive the latest (but untested) updates to openHABian as fast as possible on your system.

**Comment by ecdye** [comment]
I mostly rebased but the silly thing found lots of changes to files but no content changes (that is about 40 of those files) but other than that it rebases to master and adds the Java options.

I want to wait for Travis to complete its run and then you can give me the post link and I'll update the code and then you can push the PR.

**Comment by mstormi** [comment]
https://community.openhab.org/t/java-testdrive/99827

I've set it to 'unlisted', can you see it in the list of new posts ?
can you see it with the direct link ?

**Comment by mstormi** [comment]
BTW first Java 11 problem before we even started:
https://community.openhab.org/t/java-exceptions-at-startup-with-the-experimental-rules-engine/99819

**Comment by ecdye** [comment]
I can see it I'll update the link in the files now and then I think we are set, I'll look into the bug you mentioned after that. Part of this process is going to be relaying bugs that we find to the core dev team to make sure that they do not manifest in openHAB 3.

**Comment by ecdye** [comment]
I changed my mind, I reset it to the master and applied the commits on top this time.

**Comment by ecdye** [comment]
I'm going to close this as the main PR has been merged into master.

**Pull request closed without merging**
