### PR TITLE
Update openhabian.conf

### PR DESCRIPTION
**Pull request by udo1toni**
Clarify valid values for java-opt

Signed-off-by: Udo Hartmann [hartmann1970@gmx.de](mailto:hartmann1970@gmx.de)

### CODE REVIEW

**Review by mstormi — CHANGES_REQUESTED** [review]
add for build-image/*conf, please

**Comment by udo1toni** [comment]
Er... what? Sorry may be a dumb question...

**Comment by mstormi** [comment]
yes as a simple single look for that file pattern would have answered it
There's 3 files to match that, and your modification needs to be added to all of them.

**Comment by udo1toni** [comment]
Ah. Wasn't aware of different versions...

**Pull request merged**
