### PR TITLE
Reduce to one single openhab setup function

### PR DESCRIPTION
**Pull request by ThomDietrich**
@BClark09 

Signed-off-by: Thomas Dietrich <Thomas.Dietrich@tu-ilmenau.de>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
@BClark09 known limitation: Downgrading from snapshot to stable is not supported but the setup would still run through. I could check the installed version first (don't really want to) or I could remove the existing package (don't really want to) or I could install a specific version (I don't want that) or I could simply ignore the case because the $introtext states that downgrading is not supported. Wdyt?

**Comment by ThomDietrich** [comment]
@BClark09 the upgrade now works as discussed, without the question wether or not to replace the `/var/lib/openhab2` files. That's fine for now but openHABian shouldn't mess with these files to begin with. Do you agree? Do you think this is an important problem?

```
$ apt -y -o Dpkg::Options::=--force-confnew install openhab2
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
  openhab2
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 68.6 MB of archives.
After this operation, 16.4 MB of additional disk space will be used.
Get:1 https://openhab.jfrog.io/openhab/openhab-linuxpkg unstable/main armhf openhab2 all 2.2.0~20171216125326-1 [68.6 MB]
Fetched 68.6 MB in 1min 17s (884 kB/s)
apt-listchanges: Reading changelogs...
(Reading database ... 42515 files and directories currently installed.)
Preparing to unpack .../openhab2_2.2.0~20171216125326-1_all.deb ...
Unpacking openhab2 (2.2.0~20171216125326-1) over (2.1.0-1) ...
Setting up openhab2 (2.2.0~20171216125326-1) ...
Installing new version of config file /etc/default/openhab2 ...
Installing new version of config file /etc/openhab2/services/runtime.cfg ...
Installing new version of config file /etc/openhab2/icons/classic/readme.txt ...

Configuration file '/var/lib/openhab2/etc/org.ops4j.pax.logging.cfg'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
 ==> Using new file as you requested.
Installing new version of config file /var/lib/openhab2/etc/org.ops4j.pax.logging.cfg ...

Configuration file '/var/lib/openhab2/etc/org.apache.felix.fileinstall-deploy.cfg'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
 ==> Using new file as you requested.
Installing new version of config file /var/lib/openhab2/etc/org.apache.felix.fileinstall-deploy.cfg ...
Installing new version of config file /var/lib/openhab2/etc/shell.init.script ...

Configuration file '/var/lib/openhab2/etc/org.apache.felix.eventadmin.impl.EventAdmin.cfg'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
 ==> Using new file as you requested.
Installing new version of config file /var/lib/openhab2/etc/org.apache.felix.eventadmin.impl.EventAdmin.cfg ...

Configuration file '/var/lib/openhab2/etc/org.eclipse.smarthome.voice.cfg'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using new file as you requested.
Installing new version of config file /var/lib/openhab2/etc/org.eclipse.smarthome.voice.cfg ...

Configuration file '/var/lib/openhab2/etc/jmx.acl.org.apache.karaf.bundle.cfg'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
 ==> Using new file as you requested.
Installing new version of config file /var/lib/openhab2/etc/jmx.acl.org.apache.karaf.bundle.cfg ...

Configuration file '/var/lib/openhab2/etc/jmx.acl.org.apache.karaf.config.cfg'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
 ==> Using new file as you requested.
Installing new version of config file /var/lib/openhab2/etc/jmx.acl.org.apache.karaf.config.cfg ...

Configuration file '/var/lib/openhab2/etc/org.eclipse.smarthome.audio.cfg'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using new file as you requested.
Installing new version of config file /var/lib/openhab2/etc/org.eclipse.smarthome.audio.cfg ...
Processing triggers for systemd (232-25+deb9u1) ...
```

**Comment by BClark09** [comment]
Hi @ThomDietrich, sorry I haven't replied until now. I think that this is the best way to ensure people have a working system on upgrade. It would be ideal if we can get user configurations in the /etc/ folder only, but this is tough on Karaf.

Downgrading from unstable to stable shouldn't cause many problems either. The warning you've placed should be enough.

My only recommendation from this point would be to add that old configurations that need to be overwritten will be saved as `dpkg-old` files. Is that a good idea?

Other than that, I will try to load this new script over to the test Pi I have so that I can help test.

**Comment by ThomDietrich** [comment]
@BClark09 I've addressed your comment. Thanks!!

If you ever want to test something in the context of openHABian you should know about a hidden feature. [You'll figure it out.](https://github.com/openhab/openhabian/blob/master/functions/openhabian.sh#L34-L46)

The same goes for others. @mstormi, @EliasGabrielsson, @kubawolanin - if you ever want to contribute something. You may also add an enhancement to select other repos as well.

Okay we are ready to merge. I'll do final testing with a fresh installation in RPi0W

**Comment by BClark09** [comment]
That's really neat!

I found an error, and have made #282 to fix it. Otherwise all works great! 👍

**Pull request merged**
