### PR TITLE
Generalise stable version in menu

### PR DESCRIPTION
**Pull request by BClark09**
Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by BClark09** [comment]
I appear to have left off the > in the commit sign-off. :( Should I retry?

**Comment by ThomDietrich** [comment]
No worries. Doesn't change the validity

**Comment by ThomDietrich** [comment]
Regarding this specific entry: Previously I included it shortly after every new release. Do we want to keep it or just remove it forever?
There are the entries in "openHAB related".

Besides, How about we remove the "X"?

**Comment by BClark09** [comment]
Sure thing, I think the entry fits well on the front page, but probably should be like the entries in the "openHAB related" section.

There is the problem that the script won't actually switch to 2.3.0 stable if 2.4.0-SNAPSHOT has already been installed, but I think that may be another issue.

**Comment by ThomDietrich** [comment]
👍

**Pull request merged**
