### PR TITLE
set apt options to force installing maintainer version of OH3 config files

### PR DESCRIPTION
**Pull request by mstormi**
Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by mstormi** [comment]
merge if good

**Review by ecdye — CHANGES_REQUESTED** [review]
The change needs to be applied to both interactive and uninteractive installations, as the output will be hidden because of our `debugmode=off` setting.

**Comment by mstormi** [comment]
wdy mean - where ? to line 95 ? It shouldn't be called unattended, should it ? If so it's a new install. Or what am I missing ?

**Comment by ecdye** [comment]
I mean you only changed the offline install line. Make sure you change both.

**Comment by mstormi** [comment]
ok now?

**Comment by ecdye** [comment]
Yes looks good.

**Review by ecdye — APPROVED** [review]

**Comment by mstormi** [comment]
good. let's get 1283,1301,1302 in then forward to stable so have a look at those PRs please

I'll locally clone master into stable then force-upload.
Or have you been able to come up with a nicer solution meanwhile ?

**Comment by ecdye** [comment]
Not really, that is probably best

**Pull request merged**
