### PR TITLE
Update openhabian.md

### PR DESCRIPTION
**Pull request by sandro-byte32**
Wrong adress for progress checking

### CODE REVIEW

**Review by ecdye — APPROVED** [review]
LGTM, thanks for your contribution.

**Comment by ecdye** [comment]
@sandro-byte32 Can you fix the DCO errors, just follow the instructions given under the DCO check.

**Comment by mstormi** [comment]
Add a sentence like

"replace `openhabiandevice` if you defined `hostname` in `openhabian.conf`"

**Comment by mstormi** [comment]
Obsoleted by https://github.com/openhab/openhabian/commit/93e2bb1f651f251d145aca877acfb4aa5ada1485

**Pull request closed without merging**
