### PR TITLE
implemented shellcheck as action; preparations for build

### PR DESCRIPTION
**Pull request by holgerfriedrich**
refers to #832 
Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Comment by mstormi** [comment]
you want this to close #832 ? Or was it Github to misunderstand ?

**Comment by holgerfriedrich** [comment]
@mstormi I closed 697 manually because workaround and error message is in place; this one should not actually close 832, it is just a first step implementing shellcheck as an action and prepare for doing the image preparation via actions. This is already in place at my forked repo.

**Comment by mstormi** [comment]
understood. But note Github interpreted your "refers to ..." as it would interpret "fixes ..." so it'll close that when merging this

**Comment by mstormi** [comment]
Then again while that probably was not your intention you IMHO could leave it like that.
#832 more of an idea than a real proposal where to apply.
I like this idea of yours here to move Shellsheck from Travis to Github as contributors get feedback earlier.
But for the more complex CI stages I'd like to stay (well, in the first place, start ;-)) with Travis.

**Comment by ecdye** [comment]
True enough, #832 really was just a suggestion. It doesn't need to be implemented, and if it is better to do it in stages to adjust our already complicated build and test system.

**Comment by holgerfriedrich** [comment]
What we do not have in place right now is automated creation of the SD card image, and this is what I did with actions on my repo. Not sure if I should add this to the PR.

@mstormi If you want, you could merge this here as as starting point and we will open an new issue to explore the options for creating the image in a new issue....

**Comment by mstormi** [comment]
ok but please proceed and review #684

**Comment by mstormi** [comment]
I can see the action being excuted, but no output whatsoever such as echo OK ?
https://github.com/mstormi/openhabian/actions/runs/85147087/workflow

**Comment by ecdye** [comment]
@mstormi You have to click through to the build menu, then you can see the actions executed and look at the output of each one.

**Comment by mstormi** [comment]
I see

**Pull request merged**
