### PR TITLE
Support Homegear on Bullseye

### LINKED ISSUE #1570: Homegear broken in Bullseye currently
This is a place to track updates and eventually resolve the fact that as of now Homegear is broken in Bullseye, due to dependencies that cannot be meant currently. Hopefully will be resolved with the next release of Homegear.

### PR DESCRIPTION
**Pull request by ecdye**
Fixes #1570

Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Review by mstormi — APPROVED** [review]
LGTM DNT

**Comment by mstormi** [comment]
The BATS test is still failing though it's a repo issue (in CI only?)
https://github.com/openhab/openhabian/runs/4718804976?check_suite_focus=true

**Comment by ecdye** [comment]
> The BATS test is still failing though it's a repo issue (in CI only?)
> https://github.com/openhab/openhabian/runs/4718804976?check_suite_focus=true

Not, sure. I haven't had time to test on real hardware so I'm going to hold off on merging until I do. I would like to figure out what the issue is because I don't want to push the update if it is still broken.

**Review by mstormi — APPROVED** [review]
So that BATS is working now you can merge I think

**Comment by ecdye** [comment]
Yeah, I had to use the Debian repo that Homegear provided not the RPi one as it was broken but it works so for the moment I'll leave it and merge.

**Pull request merged**
