### PR TITLE
Add support for FIND3

### LINKED ISSUE #632: Update FIND optional package to version 3
A new major rewrite of the FIND framework have been released. Would be nice have our script updated as well to install that version.

### PR DESCRIPTION
**Pull request by ecdye**
Fixes #632

Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Comment by mstormi** [comment]
Just a question, Configuring before Compiling & Installing ?

2020-08-07_20:37:06_CEST [openHABian] Configuring FIND3... OK
2020-08-07_20:37:07_CEST [openHABian] Installing required packages for FIND3... OK
2020-08-07_20:43:12_CEST [openHABian] Downloading FIND3 source... OK
2020-08-07_20:43:34_CEST [openHABian] Installing Go... OK
2020-08-07_20:48:33_CEST [openHABian] Building FIND3 server... OK
2020-08-07_20:57:15_CEST [openHABian] Installing FIND3 server... OK
2020-08-07_20:57:15_CEST [openHABian] Installing FIND3 AI...

**Comment by mstormi** [comment]
Do you expect 350MB of data ???

dir     lz4     100M            350M            /opt/find3/server/main          /find3.bind

**Comment by ecdye** [comment]
> Just a question, Configuring before Compiling & Installing

It is the user configuration input that is why it says that. 

No idea. I told you it was a random, somewhat exaggerated guess. You can change it if you want.

**Comment by mstormi** [comment]
Ok FIND3 installs properly but doesn't work well yet for me.
Does it work for you?
Agree it's been a long time I worked with it but I'm missing some important stuff.
Where's the logfile ?
I've managed to learn some rooms but in 'tracking' mode I never get output. Now my app even says it cannot connect any more. 
So struggling to debug. Again, looking for the logfile....

**Comment by mstormi** [comment]
RuntimeDirectory= in find... .service must not have an absolute path (just relative)

**Pull request merged**
