### PR TITLE
debug frontail BATS

### PR DESCRIPTION
**Pull request by mstormi**
Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by mstormi** [comment]
yeah I inserted a journalctl -xu to see startup log but it says it has no journal  :(

**Comment by ecdye** [comment]
Is it maybe because the `openhab` and `openhabian` groups have not been created properly and so the service is failing to start?

**Comment by mstormi** [comment]
let's not guess wildly but insert debug statements that give more hints.
Although I must say I don't know what to look for ATM.

**Comment by ecdye** [comment]
> let's not guess wildly but insert debug statements that give more hints.
> Although I must say I don't know what to look for ATM.

Fair enough, but I have to leave now and probably won't have time to do much more testing today so for now you are on your own.

**Comment by mstormi** [comment]
ok

**Comment by mstormi** [comment]
I didn't get it to work it's as if chmod/setfacl does not take effect.
So I changed login shell and homedir to /var/tmp instead.

**Comment by mstormi** [comment]
So are we set for the image release ?

**Comment by ecdye** [comment]
I think so, how about we let master settle until Saturday (ie try not to merge anything unless critical) and then sync master to stable and create the final image and upload and announce it.

**Comment by mstormi** [comment]
Ok will do like that.
Please cross-check the docs & NEWS in the meantime.

**Pull request closed without merging**
