### PR TITLE
Update wifi function for stretch, resolves #374

### LINKED ISSUE #374: Detect RPi3B+
https://community.openhab.org/t/raspberry-3-b-wifi-on-openhabian/43417

@mues-lee could you troubleshoot this problem for me?

My guess: This routine doesn't match the new Pi, hence that condition isn't true:

https://github.com/openhab/openhabian/blob/master/functions/helpers.sh#L55
https://github.com/openhab/openhabian/blob/master/functions/wifi.sh#L5

### PR DESCRIPTION
**Pull request by ThomDietrich**
Resolves #374 

@mues-lee @haroldh I just realized that we missed this change in #376 

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

### CODE REVIEW

**Comment by Josar** [comment]
I just want to mention that setting the localisation to US will lead to EIRP regulation violation for most of the user outside the US. 

If the users don't change it as they think everything works fine, you will have made them unwillingly violate national regulation.

Maybe setting a country which has less transmit power then the US would be preferable. Just as a thought.

https://www.google.de/amp/s/w.wol.ph/2015/08/28/maximum-wifi-transmission-power-country/amp/

**Comment by ThomDietrich** [comment]
That is a valid point.
At an earlier stage I didn't really care but now that the function becomes more and more popular (connect via ethernet guys! 😉) we should consider that.

Actually we can do one better. There is already a setup step to detect your devices geolocation for time zone setting. We could probably derive the country from that as well. See: https://ipstack.com

**Comment by jayloo** [comment]
Dear Josar and Thom, will you work on this [problem](https://community.openhab.org/t/raspberry-3-b-wifi-on-openhabian/43417/17) soon or should I switch to a former firmware and just go with ethernet....?

**Comment by haroldh** [comment]
Today I was finally able to get WiFi working on my new RBP3B+ !
Over the last week I have tried many different things, to mention a few:
- updating the wpa_supplicant.conf file, with country=nl (among other things)
- updating the RBP firmware to 4.14.33-v7+ #1109 SMP Tue Apr 10 17:28:38 BST 2018 armv7l
- fiddling with wpa_cli commands
- and rebooting dozens of times...
All resulting in some sort of message: wlan0: link is down

Finally i read a [post in Chinese](https://www.raspberrypi.com.tw/tag/raspberry-pi-3b-model-b-plus/) (mind you, I only able to say "ni hao") that mentioned WiFi on a RBP3B+ . From that I gathered some commands that did the trick:
`$ sudo rfkill list`, showing the current wifi:

> 0: phy0: Wireless LAN
> 	Soft blocked: yes
> 	Hard blocked: no

`$ sudo rfkill unblock wifi`
`$ sudo rfkill list`, showing the unlocked Soft block:

> 0: phy0: Wireless LAN
> 	Soft blocked: **no**
> 	Hard blocked: no

Now I have both eth0 and wlan0 active! Look at the output of `ifconfig` :

> eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.200.143  netmask 255.255.255.0  broadcast 192.168.200.255
>         inet6 fe80::a2b9:caf3:c9a0:7f14  prefixlen 64  scopeid 0x20<link>
>         ether b8:27:eb:0b:0e:83  txqueuelen 1000  (Ethernet)
>         RX packets 37793  bytes 8495231 (8.1 MiB)
>         RX errors 0  dropped 2701  overruns 0  frame 0
>         TX packets 6277  bytes 620070 (605.5 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

> wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.200.146  netmask 255.255.255.0  broadcast 192.168.200.255
>         inet6 fe80::a657:b0d8:9dbb:6063  prefixlen 64  scopeid 0x20<link>
>         ether b8:27:eb:5e:5b:d6  txqueuelen 1000  (Ethernet)
>         RX packets 95  bytes 20944 (20.4 KiB)
>         RX errors 0  dropped 8  overruns 0  frame 0
>         TX packets 35  bytes 6045 (5.9 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

And `iwlist` , showing my WiFi connection details:

> wlan0     IEEE 802.11  ESSID:"OlivierHacht"
>           Mode:Managed  Frequency:5.24 GHz  Access Point: 10:C3:7B:98:32:4C
>           Bit Rate=200 Mb/s   Tx-Power=31 dBm
>           Retry short limit:7   RTS thr:off   Fragment thr:off
>           Power Management:on
>           Link Quality=69/70  Signal level=-41 dBm
>           Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
>           Tx excessive retries:0  Invalid misc:0   Missed beacon:0

If you want me to, I can post the contents of the relevant network files here. I am now focussing on getting past the next hurdle: getting the Razberry to work.

**Comment by Josar** [comment]
Dear Jeroen,

What problem are you referencing exactly?
As I know everything should work as it is at the moment, at least I think so.

It is just not set to fulfill the EIRP regulations for all countries.
So changing the country code in `/etc/wpa_supplicant/wpa_supplicant.conf` to `country=<Your Country>` should make it fulfill the regulations of your country.

Can you get wifi to work with a standard Raspbian Stretch for rpi3+?

Maybe your wifi is `soft blocked`
https://www.raspberrypi.org/forums/viewtopic.php?t=207882
https://osric.com/chris/accidental-developer/2017/09/wifi-on-raspberry-pi-3/


Von: Jeroen <notifications@github.com>
Gesendet: Samstag, 14. April 2018 11:04
An: openhab/openhabian <openhabian@noreply.github.com>
Cc: Josar <josuaarndt@live.de>; Comment <comment@noreply.github.com>
Betreff: Re: [openhab/openhabian] Update wifi function for stretch, resolves #374 (#377)


Dear Josar and Thom, will you work on this problem<https://community.openhab.org/t/raspberry-3-b-wifi-on-openhabian/43417/17> soon or should I switch to a former firmware and just go with ethernet....?

**Comment by Josar** [comment]
from:
https://www.raspberrypi.org/forums/viewtopic.php?t=207882

> If you use Raspberry Pi Configuration (rc_gui) or raspi-config, rfkill unblocks wifi. If you boot and manually modify wpa_supplicant.conf, then you'll still need to run 'rfkill unblock wifi' yourself.

@ThomDietrich maybe this has to be adressed when changing `/etc/wpa_supplicant/wpa_supplicant.conf`

**Comment by ThomDietrich** [comment]
@haroldh great find. @jscottnz came to the same conclusion and already opened a PR. Could you please compare your findings? https://github.com/openhab/openhabian/pull/380

@Josar the country code detail is - let's call it the next step. We should definitely look into it. I'd hope there is an existing script out there. Probably a matter of seconds to find it. Would you be so kind to check and also create a new specific issue for it?

**Comment by jscottnz** [comment]
Hi guys. I briefly scanned the comments about the country code. I also noticed this in the weekend and took a stab at it:
https://github.com/openhab/openhabian/pull/384

**Pull request merged**
