### PR TITLE
Changed "Manual/Fresh Setup" menu to checklist

### LINKED ISSUE #250: Menu "Manual/Fresh Setup" as checklist
grafik

https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail

Instead of `whiptail --menu` we should use `whiptail --checklist` to speed up and reduce the work for Manual Setup users. Besides a change in the menu the evaluation of what was selected has to happen. A working example can be found in the serial port function.

https://github.com/openhab/openhabian/blob/master/functions/system.sh#L272

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
Fixes #250

Signed-off-by: Elias Gabrielsson <elias@benefactory.se> (github: EliasGabrielsson)

### CODE REVIEW

**Comment by ThomDietrich** [comment]
😲 great one Elias! Thanks for looking into the issue. Looks good to me, I trust you've tested it properly.

**Comment by EliasGabrielsson** [comment]
It's tested and it works for me™. Missed the conflict, will fix the variable name.

**Comment by EliasGabrielsson** [comment]
@ThomDietrich Done

**Comment by ThomDietrich** [comment]
Thanks!

**Pull request merged**
