### PR TITLE
add Ubuntu support

### LINKED ISSUE #926: Ubuntu support
Ubuntu clearly is the most popular Linux flavour for x86.
As we don't provide images for x86, I think we need to support it to gain a broader openHABian user base. As most packages are identical to Debian I wouldn't think it'll be much effort.

- [x]  Code cleanup to remove or update Ubuntu references
- [x]  Travis test case with proper Docker Ubuntu image (focal and bionic LTS releases) => #975
- [x]  docs update

### PR DESCRIPTION
**Pull request by mstormi**
Fixes #926 

Added a travis test case

What else do we need ?

Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by mstormi** [comment]
@ecdye what's the Balena image list you used ? 
In https://www.balena.io/docs/reference/base-images/base-images-ref/ there's no `amd64-debian`

**Comment by ecdye** [comment]
That's the one I used, `amd64-debian` is just a generic one that they provide. It is not listed on the list.

**Comment by mstormi** [comment]
@ecdye @holgerfriedrich please review.

What's left we need to desclare Ubuntu supported ?

**Comment by ecdye** [comment]
Hmm, test and fix Ubuntu specific bugs as they arise is the biggest thing left.

**Comment by mstormi** [comment]
of course but that's no prerequisite.
Ok so is there anything we would need to change in the docs ?
Else it's just about waiting, isn't it.

**Comment by ecdye** [comment]
I think we are pretty much done. Just wait and fix any bugs now.

**Pull request merged**
