### PR TITLE
Fix locale generation

### PR DESCRIPTION
**Pull request by mstormi**
broken by shellcheck change but the problem possibly already existed before

let's also see what it does to #706 as I cannot reproduce that at the moment

Signed-off-by: Markus Storm markus.storm@gmx.net

### CODE REVIEW

**Comment by ThomDietrich** [comment]
> problem possibly already existed before

How do you mean? Do these parts of the code work after the change?

**Comment by mstormi** [comment]
I did not see any issue filed for this but locale generation definitely is broken right now and this fixes it. In addition it _may_ also fix #706. But that I cannot verify because I don't see that problem on my test box.

**Comment by Homey-GER** [comment]
I can confirm it fixed several issues regarding locales.
No more errors in install log, no more console warnings and changing locales via `openhabian-config` also works again. The /etc/default/locale file was always messed up before.

My 'locale' looked like this after a few attempts to change the locale via `openhabian-config`, all in a single line and repeated multiple times.

> `#  File generated by update-locale`
> LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_CTYPE=en_GB.UTF-8 LANGUAGE=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_CTYPE=en_GB.UTF-8 LANGUAGE=en_GB.                                                             UTF-8 LC_CTYPE=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_CTYPE=en_GB.UTF-8 LANGUAGE=en_GB.UTF-8 LANGUAGE=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_CTYPE=en_GB.UTF-8 LANGUAGE=en_GB.UTF-                                                             8


after applying his patch, all is fine:
> `#  File generated by update-locale`
> LANG=en_GB.UTF-8
> LC_CTYPE=en_GB.UTF-8
> LC_ALL=en_GB.UTF-8
> LANGUAGE=en_GB.UTF-8

**Comment by ThomDietrich** [comment]
In this case I'm going to merge, irrespective of travis complaints. What's the situation on that front?

**Comment by mstormi** [comment]
> What's the situation on that front?

Well, I used to have tests execute properly (auto install on VM) albeit with some issues left. But my buildsystem changes aren't merged yet (#681 up to #684). Elias also changed some things on java and its tests.
We should merge those changes of mine first then see what's left to do.

**Pull request merged**
