### PR TITLE
Improved Grafana installation for slow systems

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
Fixes: #562

Signed-off-by: Elias Gabrielsson <elias@gabson.se>

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
@ThomDietrich Ready for review -> merge

**Comment by ThomDietrich** [comment]
Why did you remove the last step?

**Comment by EliasGabrielsson** [comment]
It's exactly the same code copied twice. 
Cleaning up my shit  so to speak,  must been really tried when initially wrote it. 😴

**Comment by ThomDietrich** [comment]
Ah, right 😄

**Pull request merged**
