### PR TITLE
[WIP] Fix JS Scripting npm install  & Display warning in case of breaking changes

### PR DESCRIPTION
**Pull request by florian-h05**
After releasing a new major version of openhab-js, I noticed that "npm install openhab" does not work with new major versions. This fixes this behaviour by using the latest tag.

It checks for breaking change (new major version number) and displays a warning before upgrading, so the user can decide to upgrade later.

Signed-off-by: Florian Hotze <florianh_dev@icloud.com>

### CODE REVIEW

**Review by mstormi — APPROVED** [review]

**Comment by mstormi** [comment]
thanks

**Comment by florian-h05** [comment]
@mstormi Please wait with merging, this is actually WIP and not finished.

**Comment by mstormi** [comment]
upps :) I read WIP the moment I clicked merge

**Comment by florian-h05** [comment]
No problem.
I will provide a follow-up PR if this one needs any changes.

**Comment by mstormi** [comment]
Please do.
It's merged to main only not yet forwarded to openHAB3 branch.

**Pull request merged**
