### PR TITLE
delayed execution of installer until boot process completed

### PR DESCRIPTION
**Pull request by holgerfriedrich**
delayed start of installer, wait until multiuser target is reached
Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Comment by mstormi** [comment]
So that'll apply only if we build a new image, right?
Good all by itself thus approved it, but is there any chance to get this out without replacing the image ? Maybe as a routine called by menu option 65  ?

Also, can you check if that fixes #721 ?

**Comment by holgerfriedrich** [comment]
Partly. I delayed until multiuser target is reached. So mixing installer output with system messages is reduced.

However, Raspbian delayed some apt operations even longer, and those interfere with the installer.

I don't think I will merge that. Let me see if I can install a service, then we get rid of the rc.local messages on failed installs.

And yes, rollout is once we release a new image... I would not add this to openhabian-config. Let's red rid of those workarounds.

**Comment by mstormi** [comment]
> And yes, rollout is once we release a new image... I would not add this to openhabian-config. Let's red rid of those workarounds.



>  I would not add this to openhabian-config. Let's red rid of those workarounds.

Don't understand what you mean by 'workaround'.
I didn't mean to keep rc.local but meant to add _editing_ of systemd config to openhabian-config so anyone can benefit not just those to download the new image (once built).

**Comment by holgerfriedrich** [comment]
Just delaying does not work, will need some more efforts to correctly WiFi credentials from openhab.conf.

**Comment by gitMiguel** [comment]
Please see my https://github.com/openhab/openhabian/issues/828#issuecomment-628601940. I think that delaying until internet connectivity would solve this too.

**Comment by holgerfriedrich** [comment]
superseded by #890

**Pull request closed without merging**
