### PR TITLE
Improved PINE64 board detection

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
Signed-off-by: Elias Gabrielsson <elias@benefactory.se> (github: EliasGabrielsson)

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey Elias,
so the A64 is the only one with this chip? :)

**Comment by leonsio** [comment]
hi i have created a "little" script to detect different types of SBCs. it cat detect pine64 and pine64+ boards, and many other. you can include it in your project 

https://github.com/leonsio/arm-board-detect

i will try to add a detection of any new boards, which I can find.

**Comment by EliasGabrielsson** [comment]
@leonsio This is an amazing work.
I think we definitely should use your work.

I will close this for now and we can do a major refraction further on instead.

**Comment by ThomDietrich** [comment]
I agree.
@leonsio would you like to add a PR?

**Comment by leonsio** [comment]
ok, i will create one

**Pull request closed without merging**
