### PR TITLE
added homegear repositories for buster

### PR DESCRIPTION
**Pull request by holgerfriedrich**
added homegear repositories for Debian and Raspbian buster, as stable packages have been published

Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Comment by holgerfriedrich** [comment]
Needs testing.

**Comment by holgerfriedrich** [comment]
@EliasGabrielsson I cannot find the Travis logs... when I click the link I always get "We couldn't find the repository openhab/openhabian". Do we have a general problem or is it just me?

**Comment by EliasGabrielsson** [comment]
Strange, it should be public accessable:
Try this link: https://travis-ci.org/openhab/openhabian/builds/567382145?utm_source=github_status&utm_medium=notification
The build system is semi-stable so sometimes would the installation be restarted.

Otherwise the patch looks valid. Will merge and write a test for homegear.

**Comment by EliasGabrielsson** [comment]
And thanks by the way. 
I am really happy to see you as a new contributors to this project.
If you wonder about anything or have ideas don't hesitate to give a hint.

**Pull request merged**
