### PR TITLE
[WIP] Add fully scripted influxdb + grafana installation

### LINKED ISSUE #366: Script full Grafana & InfluxDB setup
Script the content of this post:
https://community.openhab.org/t/influxdb-grafana-persistence-and-graphing/13761/1

See password change function for influx as inspiration how to handle databases.

### LINKED ISSUE #437: Update Grafana to official ARM repository
If I read it correctly https://github.com/fg2it/grafana-on-raspberry is discontinued, due to the arm support of [Grafana 5.2](https://grafana.com/grafana/download/5.2.3?platform=arm). See https://github.com/fg2it/grafana-on-raspberry/wiki#state-end-of-life

Please fix packages.sh accordingly, so we can get past version 5.1.4

Sowhere here around L442 I guess?!
https://github.com/openhab/openhabian/blob/ecf59c4227acf79f38f0f396be26ea379f5c6e8e/functions/packages.sh#L442

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
Closes #366
Partly resolves #437

This patch aims to script the installation instructions found:
https://community.openhab.org/t/influxdb-grafana-persistence-and-graphing/13761

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
Things left todo:
* Verify functionality on 32bit ARM eg. RPi2
* Verify functionality on 64bit ARM eg. RPi3 + Pine64
* Revise menu text and structure
* Modularise installation to functions so Grafana and InfluxDB can be picked individually

**Comment by EliasGabrielsson** [comment]
@tylerbinski Thanks for testing out!
The Grafana installation is one of the regression bugs trying to be fixed in this patch.
Didn't look like fully succeeded yet. I will look into it around!

Do you miss any other features in general regarding InfluxDB and Grafana?

**Comment by tylerbinski** [comment]
@EliasGabrielsson   Sounds good!  I manually merged/updated the two files on a fresh installation (with my suggested code edits above) and it worked!  

This is a good piece of code that saves some extra steps for new users.  I hope to see it in the stable build soon!  Let me know if I can be of further assistance. 

If you need additional testing let me know.

**Comment by EliasGabrielsson** [comment]
If you have time to spare please make a PR to my branch and I will include it.
https://github.com/EliasGabrielsson/openhabian/tree/influxdb

Otherwise I will include it sometime in near™ future

**Pull request merged**
