### PR TITLE
Add ability to setup static ip on first boot

### PR DESCRIPTION
**Pull request by thedannymullen**
Add the ability to setup static ip using the dhcpcd.conf file on first boot.

This is done by modifying the file config_static_ip_template.txt and renaming to config_static_ip.txt.

The changes will be concatenated to /etc/dhcpcd.conf.

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
Hi!
Glad to see that you manage to do a PR. 👍 
I am currently focus on closing PR & issues for milestone 1.5 so this will be on hold for a little while.

// Elias

**Comment by ThomDietrich** [comment]
Just a short comment, no full review :)
Please consider changing the txt file to an ini file (for the sake of syntax highlighting)

**Comment by ThomDietrich** [comment]
Hey all,
why did you decide to creat new txt file even though we have an `openhabian.conf` exactly for changes like this? Please move them over there.

**Comment by mstormi** [comment]
Hi @thedannymullen would you please refactor your patch, making use of /etc/openhabian.conf to define inputs ?

**Comment by thedannymullen** [comment]
It has been a while since I wrote this up.  
I can add to openHAB.conf, I believe the reason I made a separate file was to prove the concept.  
I will look at it again and see what I can do.

**Comment by thedannymullen** [comment]
Do we still want this feature added?  I wrote the items to help someone that filed an issue.  I don't mind fixing the requests that you have in the PR, but would be unable to for roughly 10days from now.  

I am happy closing the PR without merging as we have had no other requests for this in almost 1.5 yrs.

**Comment by mstormi** [comment]
Alright. Background of my request was that for openHABian development, we just agreed to focus on reliability and keep the feature add rate low. Now given you yourself are questioning the need and mention there has not been any request at large, I'd agree we should probably not add it any more at least for the time being.
So I'll close the PR for now. But it'll still be in the Github archives so if needs change you or we can reanimate it at any time. Just reopen the PR when you think the time has returned.
Thanks for your contribution.

**Comment by thedannymullen** [comment]
@mstormi Thanks!  Agreed with this thought.

**Pull request closed without merging**
